### ISSUE TITLE
Passing directly send-keys

### ISSUE THREAD

**Issue by mahemoff** [tmuxinator/tmuxinator#100]
Is there any way to pass a sequence directly to send-keys? For example, this doesn't work as intended, because the C-m isn't transformed to a carriage return:

```
tabs:
    - server: ssh user@server.com C-m cd app; tail -f log
```

**Comment by zerovectorspace** [comment]
For those searching for ways to send key combinations to panes to manipulate programs like vim, you'll need to use `tmux send-keys` in a separate window.

``` yaml
name: session-name
root: ~/

windows:
  - win1:
      panes:
        - pane1:
          - echo "do something"
        - pane2:
          # - This pane holds vim
  - setup:
    # session-name:win1.1 == <session-name>:<window-name>.<pane-index>
    - tmux send-keys -t session-name:win1.1 "vim -c \"bel sp | term\" main.c" C-m # Open vim with terminal at bottom
    - tmux send-keys -t session-name:win1.1 ":resize 8" C-m # Resize terminal
    - tmux send-keys -t session-name:win1.1 "iecho \"Some commands\"" C-m # Run some command
    - sleep 1 # Sleep (in this window) if command is slow
    - tmux send-keys -t session-name:win1.1 C-\\ C-n # Go to vim normal mode
    - tmux send-keys -t session-name:win1.1 C-W C-K # Move to top split
    - exit # Kill this tmux window
```
