### ISSUE TITLE
link-window support

### ISSUE THREAD

**Issue by mikea** [tmuxinator/tmuxinator#105]
Tmuxinator should support link-window command. Main use-case is sharing window between various sessions. E.g. sharing IRC client.

**Comment by DavidRivers** [comment]
This would be an excellent feature as it would allow me to reuse windows in layouts for different monitor sizes (e.g., my work setup with 2 large external displays vs. laptop only).

**Comment by akofink** [comment]
I know this is a really really old issue, but fwiw, you don't really need support in tmuxinator to do this. You can use a project with the `link-window` command, like this:

```yaml
name: project1
root: /tmp

windows:
  - window1:
      panes:
        - pane1:
          - echo foo
          - echo bar
        - pane2:
          - echo foo
          - echo bar
  - window2:
      panes:
        - pane1:
          - echo foo
          - echo bar
        - pane2:
          - tmux link-window -s project2:1 -t :3
          - echo foo
          - echo bar
```

It seems unlikely we'd somehow add support for it in the project config. If this workaround doesn't work for you, please reopen the issue and let me know why it doesn't.
