### ISSUE TITLE
Can't run the first window tab

### ISSUE THREAD

**Issue by krzkrzkrz** [tmuxinator/tmuxinator#126]
So im running tmuxinator. my yml file looks like: 

```
name: foo 
root: ~/Sites/foo 
windows: 
  - editor: vim 
```

It opens up one window (previously known as a tab), called editor. but doesnt run vim. how come?

I also tried:

```
name: foo 
root: ~/Sites/foo 
windows:
  - editor: vim
  - console: rails c
```

The strange thing is, it opens up one window (tab), called editor. Editor runs rails c, instead of vim

I am using Tmuxinator 0.6.2
