### ISSUE TITLE
can't find pane

### ISSUE THREAD

**Issue by Lordnibbler** [tmuxinator/tmuxinator#137]
I just installed tmuxinator 0.6.4 for the first time.  When setting up a window with mulitple panes, the panes are created correctly, but none of the code in them is executed.  I also receive the following error output:

``` zsh
~ mux project
can't find pane: 1
can't find pane: 1
can't find pane: 1
arranging in: main-vertical
can't find pane: 2
can't find pane: 2
can't find pane: 2
arranging in: main-vertical
can't find pane: 3
can't find pane: 3
can't find pane: 3
arranging in: main-vertical
can't find pane: 1
can't find pane: 1
arranging in: even-horizontal
can't find pane: 2
can't find pane: 2
arranging in: even-horizontal
```

My config is the example config generated automatically:

``` yaml
# ~/.tmuxinator/.yml
# you can make as many tabs as you wish...

name: sample
root: ~/test
socket_name: foo # Remove to use default socket
pre: # sudo /etc/rc.d/mysqld start # Runs before everything
pre_window: rbenv shell 2.0.0-p247 # Runs in each tab and pane
tmux_options: -v -2 # Pass arguments to tmux
windows:
  - editor:
      pre:
        - echo "I get run in each pane, before each pane command!"
        -
      layout: main-vertical
      panes:
        - vim
        - #empty, will just run plain bash
        - top
  - shell: git pull
  - guard:
      layout: tiled
      pre:
        - echo "I get run in each pane."
        - echo "Before each pane command!"
      panes:
        -
        - #empty, will just run plain bash
        -
  - database: bundle exec rails db
  - server: bundle exec rails s
  - logs: tail -f log/development.log
  - console: bundle exec rails c
  - capistrano:
  - server: ssh user@example.com
```

I also get 1000+ of these log files in my `~/` dir: `tmux-client-68360.log`
