### ISSUE TITLE
man tmux not worked properly

### ISSUE THREAD

**Issue by speed-of-light** [tmuxinator/tmuxinator#150]
Originally I thought my issue like #101 #134 
But after I tried the following code, and several tried to modify the source code, 
I have totally no idea about why to cause this.

```
name: default 
root: ~/
windows:
  - editor:
     layout: main-vertical
     panes:
      - man tmux
      - ls
```

with `tmux ls`: `failed to connect to server`
run `mux default`
The left pane's output was not as expected (which should be a man page):
Output:

```
No manual entry for tmux                                                       
See 'man 7 undocumented' for help when manual pages are not available.
```

But if I have at least one tmux session start from current shell.
with `tmux ls`: `0: 1 windows`
run `mux default`
All works fine.
