### ISSUE TITLE
Custom layouts dont seem to work

### ISSUE THREAD

**Issue by krzkrzkrz** [tmuxinator/tmuxinator#152]
Following the instructions at: http://stackoverflow.com/questions/9812000/specify-pane-percentage-in-tmuxinator-project

On Ubuntu 13.04, tmuxinator 0.6.2, tmux 1.7

I get:

```
can't set layout: 174e,207x57,0,0{143x57,0,0,0,63x57,144,0,7}]
arranging in: main-horizontal
[server exited]
```

```
name: foo
root: ~/Sites/foo
# socket_name: foo # Not needed. Remove to use default socket
# rvm:
# pre:
# pre_window:
# tmux_options: -v -2
windows:
  - editor:
      layout: '174e,207x57,0,0{143x57,0,0,0,63x57,144,0,7}]'
      panes:
        - vim
        - # empty
  - console: git status &&rails c
  - server:
      layout: main-horizontal
      panes:
        - whenever && unicorn -p 3000 -c ./config/unicorn.rb
        - sidekiq
        - rake test && tail -f log/development.log
  - irc: weechat-curses
```
