### ISSUE TITLE
Parsing command line beginning with comma

### ISSUE THREAD

**Issue by mahemoff** [tmuxinator/tmuxinator#160]
I found a possible issue with the new multi-line syntax for commands (#100). 

A command starting with a comma like this:
    - editor:
      - vim
      - ,n
causes the error, "Failed to parse config file. Please check your formatting."

Maybe it's YAML related.

**Comment by dianapinkberry** [comment]
I have some error, but quotes not working. Can you please help me

My voltron.yml 
                                                                                                   
       # ~/.tmuxinator/voltron.yml
       
       name: voltron
       root: ~/
    
      
      windows:
        - editor:
            layout: 15a8,169x41,0,0{147x41,0,0[147x13,0,0{81x13,0,0,60,65x13,82,0,61},147x19,0,14,62,147x7,0,34{89x7,0,34,63,57x7,90,34,64}],21x41,148,0,65}
             panes:
               - voltron view disasm
               - voltron view bp
               - lldb
               - voltron view stack
               - voltron view bt
               - voltron view reg
        - server: bundle exec rails s
        - logs: tail -f log/development.log

I run  `tmuxinator start voltron`,but output I get is `Failed to parse config file. Please check your formatting.`

**Comment by adamstrickland** [comment]
Check the syntax of your YAML file.  Just eyeballing what you posted (assuming that's verbatim), it looks like you have some leading spaces before `name` and `root`, and `panes` and it's children should be shifted left one space (`panes` should be indented 2 spaces underneath `editor`, left-aligning with `layout`.

YAML can be very picky about spacing.  You may want to try something like <http://yaml-online-parser.appspot.com/> to make sure yours is correct.

**Comment by dianapinkberry** [comment]
Thank you)I changed voltron.yml. Maybe I wrong understand?(
Now I run `tmuxinator start voltron` and get error `Your project file should include some windows.`


```
 voltron.yml                                                                                                
   # ~/.tmuxinator/voltron.yml
  
   name:voltron
   root:~/

  
  windows:
    - madhax:
        layout: 15a8,169x41,0,0{147x41,0,0[147x13,0,0{81x13,0,0,60,65x13,82,0,61},147x19,0,14,62,147x7,0,34{89x7,0,34,63,57x7,90,34,64}],21x41,148,0,65}
               panes:
                  -voltron view disarm
                  -voltron view bp
                  -lldb
                  -voltron view stack
                  -voltron view bt
                  -voltron view reg
    - server: bundle exec rails s
    - logs: tail -f log/development.log

**Comment by ethagnawl** [comment]
@dianapinkberry It looks like there are still some whitespace issues happening here. Specifically, the first three lines (of content) should be left-aligned; the lack of space between the key/value in `name` and `root`.

I was able to get it working by changing it to [the following](https://gist.github.com/ethagnawl/3e1af683eb44057188cc2fdd0bbb9d79):

```
# ~/.tmuxinator/voltron.yml
name: voltron
root: ~/
windows:
  - madhax:
    layout: 15a8,169x41,0,0{147x41,0,0[147x13,0,0{81x13,0,0,60,65x13,82,0,61},147x19,0,14,62,147x7,0,34{89x7,0,34,63,57x7,90,34,64}],21x41,148,0,65}
    panes:
      - voltron view disarm
      - voltron view bp
      - lldb
      - voltron view stack
      - voltron view bt
      - voltron view reg
  - server: bundle exec rails s
  - logs: tail -f log/development.log
```

HTH! :]
