### ISSUE TITLE
Pre_window command doesn't work on pane

### ISSUE THREAD

**Issue by kithokit** [tmuxinator/tmuxinator#165]
Hello,

after upgrading to 0.6.5 I encounter error, when I tried to run command in multi pane windows, the pre_command set doesn't run

```
root: ~/
pre_window: ssh testvm
windows:
  - mainconsole:
  - rake: g cloud && rake c
  - ok: g cloud && rackup
  - cat: g portal && rails s
  - jobs:
      layout: even-vertical
      panes:
          -
          -
```

other normal windows are able to do ssh testvm command
but for panes , it can't
