### ISSUE TITLE
Tmuxinator opening only on window

### ISSUE THREAD

**Issue by karellm** [tmuxinator/tmuxinator#168]
Hi,

`mux` is only the first window from my yml config file. Any idea what is going on?

```
name: bla
root: /
pre: rm .zeus.sock
windows:
  - cmd:
      layout: main-vertical
      panes:
        - zeus start
        - 
  - server: zeus s
  - test:
      layout: 4020,238x61,0,0{140x61,0,0,97x61,141,0}
      panes:
        - bundle exec guard -p
        - 
  - console: zeus c
```

I'm running version 0.6.5 and the output of the debug is:

```
#!/bin/bash
tmux start-server\; has-session -t dashboard 2>/dev/null

if [ "$?" -eq 1 ]; then
  cd /

  # Run pre command.
  rm .zeus.sock

  # Create the session and the first window.
  TMUX= tmux new-session -d -s dashboard -n cmd

  # Set the default path.
  tmux set-option -t dashboard default-path / 1>/dev/null

  # Create other windows.
  tmux new-window -c / -t dashboard:2 -n server
  tmux new-window -c / -t dashboard:3 -n test
  tmux new-window -c / -t dashboard:4 -n console


  # Window "cmd"


  tmux send-keys -t dashboard:1.1 zeus\ start C-m

  tmux splitw -t dashboard:1
  tmux select-layout -t dashboard:1 main-vertical




  tmux select-layout -t dashboard:1 main-vertical


  tmux select-pane -t dashboard:1.1

  # Window "server"

  tmux send-keys -t dashboard:2 zeus\ s C-m

  # Window "test"


  tmux send-keys -t dashboard:3.1 bundle\ exec\ guard\ -p C-m

  tmux splitw -t dashboard:3
  tmux select-layout -t dashboard:3 4020,238x61,0,0\{140x61,0,0,97x61,141,0\}




  tmux select-layout -t dashboard:3 4020,238x61,0,0\{140x61,0,0,97x61,141,0\}


  tmux select-pane -t dashboard:3.1

  # Window "console"

  tmux send-keys -t dashboard:4 zeus\ c C-m

  tmux select-window -t 1
fi

if [ -z "$TMUX" ]; then
  tmux -u attach-session -t dashboard
else
  tmux -u switch-client -t dashboard
fi
```

What happens is that the `cmd` window open but none of the following.

Thanks
