### ISSUE TITLE
Can't name a pane without running a command

### ISSUE THREAD

**Issue by dbingham** [tmuxinator/tmuxinator#173]
I put together a project like this:

```
# ~/.tmuxinator/dev.yml

name: dev
root: ~/

windows:
  - Main:
      layout: e1ef,425x28,0,0{111x28,0,0,0,313x28,112,0,2}
      panes:
        - tig:
          - cd /Users/dbingham/Development/git/main
          - tig --all
        - sh:
          - cd /Users/dbingham/Development/git/main
          - clear
  - dev: 
      layout: e1ef,425x28,0,0{111x28,0,0,0,313x28,112,0,2}
      panes:
        - tig:
          - tmux set-window-option automatic-rename on
          - clear
        - sh:
```

When I try `mux start dev` I get the following:

```
(erubis:38:in `block (2 levels) in render': undefined local variable or method `commands' for #<Tmuxinator::Project:0x007f9a01477e10> (NameError)
    from (erubis:30:in `each'
    from (erubis:30:in `block in render'
    from (erubis:21:in `each'
    from (erubis:21:in `render'
    from /Users/dbingham/.rvm/gems/ruby-2.0.0-p247/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `eval'
    from /Users/dbingham/.rvm/gems/ruby-2.0.0-p247/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `result'
    from /Users/dbingham/.rvm/gems/ruby-2.0.0-p247/gems/tmuxinator-0.6.6/lib/tmuxinator/project.rb:14:in `render'
    from /Users/dbingham/.rvm/gems/ruby-2.0.0-p247/gems/tmuxinator-0.6.6/lib/tmuxinator/cli.rb:59:in `start'
    from /Users/dbingham/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
    from /Users/dbingham/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
    from /Users/dbingham/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
    from /Users/dbingham/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
    from /Users/dbingham/.rvm/gems/ruby-2.0.0-p247/gems/tmuxinator-0.6.6/bin/mux:16:in `<top (required)>'
    from /Users/dbingham/.rvm/gems/ruby-2.0.0-p247/bin/mux:23:in `load'
    from /Users/dbingham/.rvm/gems/ruby-2.0.0-p247/bin/mux:23:in `<main>'
    from /Users/dbingham/.rvm/gems/ruby-2.0.0-p247/bin/ruby_executable_hooks:15:in `eval'
    from /Users/dbingham/.rvm/gems/ruby-2.0.0-p247/bin/ruby_executable_hooks:15:in `<main>'
```

But if I replace the last line (`- sh:`) with `- #bash` it works.
