### ISSUE TITLE
Window command in second window operates on first window

### ISSUE THREAD

**Issue by dbingham** [tmuxinator/tmuxinator#174]
I have the following project:

```
# ~/.tmuxinator/dev.yml

name: dev
root: ~/

windows:
  - Main:
      layout: e1ef,425x28,0,0{111x28,0,0,0,313x28,112,0,2}
      panes:
        - tig:
          - cd /Users/dbingham/Development/git/main
          - tig --all
        - sh:
          - cd /Users/dbingham/Development/git/main
          - clear
  - dev: 
      layout: e1ef,425x28,0,0{111x28,0,0,0,313x28,112,0,2}
      panes:
        - tig:
          - tmux set-window-option automatic-rename on
          - clear
        - #bash
```

The `tmux set-window-option automatic-rename on` on the second window actually ends up setting that option on the *first* window when I run `mux start dev`.  The second window is unaffected and is still named 'dev'.

By way of workaround, is there a way to _not_ name a window when creating it?
