### ISSUE TITLE
Set per window root directory

### ISSUE THREAD

**Issue by dbingham** [tmuxinator/tmuxinator#175]
Is there a way to specify a per-window root directory?  The equivalent of the `-c` option to the `tmux new-window` command?

If not, I'd like to request that as a feature.

**Comment by ae35unit** [comment]
+1 - how does this feature still not exist?

**Comment by imakewebthings** [comment]
The changelog indicates this was added in 0.6.10 but I don't see it working in that version either. Can anyone confirm that it works for them and that I am just, somehow, being a bad user?

**Comment by Soliah** [comment]
This should be working now.

**Comment by ChillarAnand** [comment]
Is there a way to run specific command on all panes in a window?

**Comment by adamstrickland** [comment]
@ChillarAnand look at the `synchronize

**Comment by Pablo1107** [comment]
For people watching now, there is and option the run a command in every pane before all other commands. 

```
  - server:
      layout: 6742,134x111,0,0[134x55,0,0,0,134x55,0,56{67x55,0,56,1,66x55,68,56,2}]
      pre: cd ~/code/your-project-name
      panes:
        - vim
        - docker-compose up -d; clear
```

**Comment by brobertsaz** [comment]
I run two apps so I set the root at the top of the file for one apps path and then override the 2nd app with pre like @Pablo1107 suggested:
```
windows:
  - UAPP:
  - UAPP-Servers:
      layout: main-horizontal
      panes:
        - brs -p 3001
        - bundle exec sidekiq
  - UAPP-Console: 
      panes: 
        - brc
  - UNODE: cd ~/PO2/u-node
  - UNODE-Servers:
      layout: main-horizontal
      pre: cd ~/PO2/u-node
      panes:
        - brs
        - bundle exec sidekiq
```
