### ISSUE TITLE
mux start [project] returns "no sessions"

### ISSUE THREAD

**Issue by Priezt** [tmuxinator/tmuxinator#178]
If I do "mux debug [project] | source /dev/stdin", the tmux session will be successfully created and attached.
But if I do "mux start [project]" or "mux [project]", only returns "no sessions".
Reproducible on two FreeBSD machines with tmux version 1.7 and 1.8.

**Comment by hcontreras** [comment]
Same problem... :(

OS X Maverics
tmux: 1.8
mux: 0.6.10

First, checking if everything's ok.
```
$~ mux doctor
Checking if tmux is installed ==> Yes
Checking if $EDITOR is set ==> Yes
Checking if $SHELL is set ==> Yes
```
This is what I did...
```
 ~$ mux new project1
```
Here's my project.yml file

```
# ~/.tmuxinator/project1.yml
name: project1
root: ~/

windows:
  - editor:
      layout: main-vertical
      panes:
        - vim 
```
I run it like this

```
~$ mux project1
```
This is the result
```
new-session: illegal option -- c
usage: new-session [-AdDP] [-F format] [-n window-name] [-s session-name] [-t target-session] [-x width] [-y height] [command]
failed to connect to server
failed to connect to server
failed to connect to server
failed to connect to server
failed to connect to server
no sessions
```
What am I missing?

Help, please!
