### ISSUE TITLE
Panes doesn't start programs

### ISSUE THREAD

**Issue by simendsjo** [tmuxinator/tmuxinator#187]
I have this simple config
EDIT: Using version `0.6.6`

```
# ~/.tmuxinator/communicate.yml

name: communicate
root: ~/
socket_name: communicate
tmux_options: -f /usr/share/oh-my-zsh/plugins/tmux/tmux.extra.conf

windows:
    - communicate:
        layout: main-vertical
        panes:
            - mutt
            - irssi
```

The window and panes gets created, but `mutt` and `irssi` isn't started.

EDIT2: I just found the debug command:
`mux debug communicate`

```
#!/bin/zsh
tmux -f /usr/share/oh-my-zsh/plugins/tmux/tmux.extra.conf -L communicate start-server\; has-session -t communicate 2>/dev/null

if [ "$?" -eq 1 ]; then
  cd ~/

  # Run pre command.


  # Create the session and the first window.
  TMUX= tmux -f /usr/share/oh-my-zsh/plugins/tmux/tmux.extra.conf -L communicate new-session -d -s communicate -n communicate

  # Set the default path.
  tmux -f /usr/share/oh-my-zsh/plugins/tmux/tmux.extra.conf -L communicate set-option -t communicate default-path \~/ 1>/dev/null

  # Create other windows.


  # Window "communicate"


  tmux -f /usr/share/oh-my-zsh/plugins/tmux/tmux.extra.conf -L communicate send-keys -t communicate:1.1 mutt C-m

  tmux -f /usr/share/oh-my-zsh/plugins/tmux/tmux.extra.conf -L communicate splitw -t communicate:1
  tmux -f /usr/share/oh-my-zsh/plugins/tmux/tmux.extra.conf -L communicate select-layout -t communicate:1 main-vertical


  tmux -f /usr/share/oh-my-zsh/plugins/tmux/tmux.extra.conf -L communicate send-keys -t communicate:1.2 irssi C-m

  tmux -f /usr/share/oh-my-zsh/plugins/tmux/tmux.extra.conf -L communicate select-layout -t communicate:1 main-vertical

  tmux -f /usr/share/oh-my-zsh/plugins/tmux/tmux.extra.conf -L communicate select-pane -t communicate:1.1

  tmux -f /usr/share/oh-my-zsh/plugins/tmux/tmux.extra.conf -L communicate select-window -t 1
fi

if [ -z "$TMUX" ]; then
  tmux -f /usr/share/oh-my-zsh/plugins/tmux/tmux.extra.conf -L communicate -u attach-session -t communicate
else
  tmux -f /usr/share/oh-my-zsh/plugins/tmux/tmux.extra.conf -L communicate -u switch-client -t communicate
fi
```
