### ISSUE TITLE
Commands do not work.

### ISSUE THREAD

**Issue by zackp30** [tmuxinator/tmuxinator#195]
Is there a reason why this wouldn't launch the commands? It renames the windows correctly just not the commands:

``` yaml
name: school
root: ~/gitlab/tex/texdocuments

# Optional tmux socket
# socket_name: foo

# Runs before everything. Use it to start daemons etc.
# pre: sudo /etc/rc.d/mysqld start

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
# tmux_command: byobu

windows:
  - main:
      layout: even-vertical
      panes:
          - vim
          - pane2:
              - 'rvm use 2'
              - 'bundle exec guard'
  - stuff:
      panes:
          - vim

```
