### ISSUE TITLE
Not recognizing panes?

### ISSUE THREAD

**Issue by nathanielks** [tmuxinator/tmuxinator#204]
Hey all-

For some reason tmuxinator isn't recognizing my pane definitions...

Here's my config:

```
# ~/.tmuxinator/dev.yml

name: dev
root: /srv/foobar.com/www/app/

windows:
  - plugin:
    - cd plugins/foobar
  - logs:
    layout: main-vertical
    panes:
      - log:
        - cd plugins/foobar
        - tail -f error_log
      - js:
        - cd assets/js/frontend
        - grunt watch
  - theme:
    - cd themes/foobar
    - vim
  - project:
    - cd ../
```

and when I run `mux debug`:

```
#!/bin/zsh
tmux start-server\; has-session -t dev 2>/dev/null

if [ "$?" -eq 1 ]; then
  cd /srv/foobar.com/www/app/

  # Run pre command.


  # Create the session and the first window.
  TMUX= tmux new-session -d -s dev -n plugin

  # Set the default path.
  tmux set-option -t dev default-path /srv/foobar.com/www/app/ 1>/dev/null

  # Create other windows.
  tmux new-window -c /srv/foobar.com/www/app/ -t dev:2 -n logs
  tmux new-window -c /srv/foobar.com/www/app/ -t dev:3 -n theme
  tmux new-window -c /srv/foobar.com/www/app/ -t dev:4 -n project


  # Window "plugin"

  tmux send-keys -t dev:1 cd\ plugins/foobar C-m

  # Window "logs"


  # Window "theme"

  tmux send-keys -t dev:3 cd\ themes/foobar C-m
  tmux send-keys -t dev:3 vim C-m

  # Window "project"

  tmux send-keys -t dev:4 cd\ ../ C-m

  tmux select-window -t 1
fi

if [ -z "$TMUX" ]; then
  tmux -u attach-session -t dev
else
  tmux -u switch-client -t dev
fi
```

I can tell it's completely skipping the logs section, but I don't get why? It doesn't spit out any errors or any clues as to why it doesn't work. Any help?
