### ISSUE TITLE
Tmuxinator doesn't run commands on the created panes

### ISSUE THREAD

**Issue by canselcik** [tmuxinator/tmuxinator#225]
I am trying to use `tmuxinator` to start a `tmux` session with a single window containing four panes that have the following commands running. However, no matter what I change, the commands aren't executed and I just end up getting four panes with `bash` (or `zsh` in my case) running.

My yml file for this session:

```
# ~/.tmuxinator/testing.yml

name: testing
root: /Users/user/Desktop/DFS/DFS_Client/src/DistributedFS/out/artifacts/DistributedFS_jar

windows:
  - mp3:
      layout: tiled
      panes:
        - java -jar DistributedFS.jar ../../../settings.conf 127.0.0.1 1025
        - java -jar DistributedFS.jar ../../../settings.conf 127.0.0.1 1026
        - java -jar DistributedFS.jar ../../../settings.conf 127.0.0.1 1027
        - java -jar DistributedFS.jar ../../../settings.conf 127.0.0.1 1028
```

I have the default configuration generated by the `tmuxinator` setup. I am running on OSX 10.9 Mavericks, with `zsh` installed. I installed `tmuxinator` using `gem install tmuxinator`.

It seems the issue https://github.com/tmuxinator/tmuxinator/issues/187 is similar to mine. I tried setting the `pane-base-index` to both 0 and 1, but that didn't fix it.

What do you think?
