### ISSUE TITLE
Feature Req: Pass arguments to projects

### ISSUE THREAD

**Issue by bsodmike** [tmuxinator/tmuxinator#242]
I'm not sure if this is already supported, but I'm hoping to do things like

```
mux start ssh_run foo.bar.com
```

The first ARG is referenced within the project definition say,
```
name: sample
root: ~/

windows:
  - stats:
    - ssh $1
    - tail -f /var/log/stats.log
```

Just a thought, appreciate any feedback.
Thanks!

**Comment by edouardberthe** [comment]
:+1:  it would be great for me, I have a project with 4 main directories, and sometimes I would like to open some of them, sometimes not. I could do :
mux start project dir1 dir3 dir4

**Comment by MuschPusch** [comment]
+ 1 most of my yaml files look the 99% the same

**Comment by hersha** [comment]
Hmmmm could pass the yaml through ERB before parsing it. This would let you do lots of customization.

**Comment by hersha** [comment]
You can use ERB in the YAML files like this.
```yaml
name: sample
root: ~/

windows:
  - stats:
    - ssh <%= ARGV[n] %>
    - tail -f /var/log/stats.log
```

**Comment by J3RN** [comment]
I also vote for this issue. I've got a lot of files that are essentially:
```yaml
name: <%= ARGV[0] %>
root: ~/workspace/<%= ARGV[0] %>
...
```
