### ISSUE TITLE
Second TMUX window will not open

### ISSUE THREAD

**Issue by DVG** [tmuxinator/tmuxinator#243]
I've got the following mux configuration file

```
name: my_project
root: ~/code/projects/my_project
windows:
  - zeus-and-servers:
      layout: main-horizontal
      panes:
        - zeus:
          - zeus start
        - server:
          - sleep 1
          - zeus s
        - web-service:
          - cd ~/code/projects/my_service
          - bundle exec rails s
  - my-library: cd ~/code/gems/my_gem
```

The main window works great. But the second window, `my-library` never gets created.

mux debug at that point shows:

```
  # Window "my-library"
  tmux send-keys -t my_project:1 cd ~/code/gems/my_gem C-m
```

Which shows it trying to run the command, but I do not see it creating the actual window.

What am i missing here?
