### ISSUE TITLE
Commands in panes not running; Commands running

### ISSUE THREAD

**Issue by caleb** [tmuxinator/tmuxinator#249]
I'm having a problem with a tmuxinator configuration and for the life of me I can't figure out what's wrong.

I'm on tmuxinator 0.6.8, OS X 10.9, using rbenv and zsh 5.0.6.

Here's my configuration:

``` yaml
name: snell
root: ~/Projects/snell_luxury_rentals

windows:
  - editor:
      layout: main-vertical
      panes:
        - vim
        - bin/bundle exec guard
  - server: bin/rails s
```

When I run `mux snell` I get two windows, and the second window (`server`) starts its command, but in the first window where I have two panes, neither `vim` nor `bin/bundle exec guard` is run.

I'm guessing I'm doing something wrong, but I don't know what that could be.

-Caleb
