### ISSUE TITLE
can't use personel layout

### ISSUE THREAD

**Issue by mircsicz** [tmuxinator/tmuxinator#250]
Hi hi,

I'm trying to use layout like this:
````
layout: cbdf,238x57,0,0{119x57,0,0[119x28,0,0,1,119x28,0,29,3],118x57,120,0[118x17,120,0,4,118x20,120,18,0,118x18,120,39,2]}
````

the file look's like this

````
name: tst2
root: ~/

windows:
  - main:
        layout: cbdf,238x57,0,0[119x57,0,0{119x28,0,0,1,119x28,0,29,3},118x57,120,0{118x17,120,0,4,118x20,120,18,0,118x18,120,39,2}]
       panes:
        - vim
        - #empty, will just run plain bash
        - top
        - htop
        - df -h
````

But all it returns is: "Failed to parse config file. Please check your formatting." And I've so far tested some of my favorite system's: MacOS 10.9.4, Debian Wheezy and LMDE (LinuxMintDebianEdition), all of them are fresh "gem install'ed"...
