### ISSUE TITLE
junk shown with split panes after upgrade to tmux 1.5

### ISSUE THREAD

**Issue by figgis** [tmuxinator/tmuxinator#26]
Downloaded the latest version of tmux from http://downloads.sourceforge.net/tmux/tmux-1.5.tar.gz

```
./configure --prefix=$HOME
make
make install
```

my .tmux.conf file is empty.

installed the latest using:

`git clone https://github.com/aziz/tmuxinator.git`

and using this minimal yml-file:

```
# ~/.tmuxinator/error.yml
# you can make as many tabs as you wish...

project_name: error
project_root: ~/
tabs:
  - editor:
      layout: even-vertical
      panes:
        - #empty
        - #empty, will just run plain bash
        - #empty
```

This causes the horisontal splits to be rendered as 

```
ââââââââââââââââââââââââââââââââ
```

Same behavior in gnome-terminal as well as xterm.
Running Ubuntu 10.04

$TERM=xterm-256color

No problem creating windows/panes using tmux alone. Previously today I used an older version of tmux (the one in ubuntu repository, think it was 1.1-1) and everything worked,that version was installed in /usr/bin. Upgraded to 1.5 and installed it locally since I'm not root here at work and it doesn't work any longer.

Probably some ncurses mismatch or similar...

```
$ ldd ~/bin/tmux
    linux-vdso.so.1 =>  (0x00007fff4f1a0000)
    libutil.so.1 => /lib/libutil.so.1 (0x00007f4a2161c000)
    libm.so.6 => /lib/libm.so.6 (0x00007f4a21399000)
    libncurses.so.5 => /lib/libncurses.so.5 (0x00007f4a21155000)
    libevent-1.4.so.2 => /usr/lib/libevent-1.4.so.2 (0x00007f4a20f3b000)
    librt.so.1 => /lib/librt.so.1 (0x00007f4a20d33000)
    libc.so.6 => /lib/libc.so.6 (0x00007f4a209af000)
    libresolv.so.2 => /lib/libresolv.so.2 (0x00007f4a20796000)
    libdl.so.2 => /lib/libdl.so.2 (0x00007f4a20592000)
    libnsl.so.1 => /lib/libnsl.so.1 (0x00007f4a20377000)
    libpthread.so.0 => /lib/libpthread.so.0 (0x00007f4a2015a000)
    /lib64/ld-linux-x86-64.so.2 (0x00007f4a21845000)
```

Any ideas?

Will do the same from home this evening and see if I get same behavior.
I'll update when I have tried
