### ISSUE TITLE
Tmuxinator doing weird things...

### ISSUE THREAD

**Issue by joeguilmette** [tmuxinator/tmuxinator#261]
So when I run `$ mux work` I get the following:

```
echo this is weird, right?

 joe:mba in ~
○ → 
echo this is weird, right?

 joe:mba in ~
○ → echo this is weird, right?
this is weird, right?

 joe:mba in ~
○ → _
```

Here is `work.yml`:

```
 # ~/.tmuxinator/work.yml
 
 name: work
 root: ~/
 
 # Optional tmux socket
 # socket_name: foo
 
 # Runs before everything. Use it to start daemons etc.
 # pre: sudo /etc/rc.d/mysqld start
 
 # Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
 # pre_window: rbenv shell 2.0.0-p247
 
 # Pass command line options to tmux. Useful for specifying a different tmux.conf.
 # tmux_options: -f ~/.tmux.mac.conf
 
 # Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
 # tmux_command: byobu
 
 windows:
   - workspace:
       layout: bbfd,204x58,0,0[204x34,0,0,0,204x23,0,35{67x23,0,35,3,67x23,68,35,4,68x23,136,35,5}]
       panes:
         - echo this is weird, right?
         - cd /Code
         - #empty, will just run plain bash
         - #empty, will just run plain bash
   - servers:
        layout: bbfd,204x58,0,0[204x34,0,0,0,204x23,0,35{67x23,0,35,3,67x23,68,35,4,68x23,136,35,5}]
        panes:
         - #empty, will just run plain bash
         - mosh root@joeguilmette.com
         - mosh joeguilm@joeguilmette.com
         - #empty, will just run plain bash
   - vim:
        layout: b7a6,204x58,0,0{125x58,0,0,2,78x58,126,0[78x28,126,0,9,78x29,126,29,10]}
        panes:
         - vim
         - #empty, will just run plain bash
         - #empty, will just run plain bash
```

To `tmux.conf` I have added: 

```
 set -g base-index 1
 set -g pane-base-index 1
```

Here is a mux debug output for you:

```
 #!/bin/bash

# Clear rbenv variables before starting tmux
unset RBENV_VERSION
unset RBENV_DIR

tmux start-server\; has-session -t work 2>/dev/null

if [ "$?" -eq 1 ]; then
  cd /Users/joe

  # Run pre command.
  

  # Create the session and the first window.
  TMUX= tmux new-session -d -s work -n workspace


  # Create other windows.
  tmux new-window -c /Users/joe -t work:1 -n servers
  tmux new-window -c /Users/joe -t work:2 -n vim


  # Window "workspace"
  
  tmux send-keys -t work:0.0 '' C-m
  tmux send-keys -t work:0.0 echo\ this\ is\ weird,\ right\? C-m

  tmux splitw -t work:0
  tmux select-layout -t work:0 bbfd,204x58,0,0\[204x34,0,0,0,204x23,0,35\{67x23,0,35,3,67x23,68,35,4,68x23,136,35,5\}\]
  
  tmux send-keys -t work:0.1 '' C-m
  tmux send-keys -t work:0.1 cd\ /Code C-m

  tmux splitw -t work:0
  tmux select-layout -t work:0 bbfd,204x58,0,0\[204x34,0,0,0,204x23,0,35\{67x23,0,35,3,67x23,68,35,4,68x23,136,35,5\}\]
  
  tmux send-keys -t work:0.2 '' C-m
  

  tmux splitw -t work:0
  tmux select-layout -t work:0 bbfd,204x58,0,0\[204x34,0,0,0,204x23,0,35\{67x23,0,35,3,67x23,68,35,4,68x23,136,35,5\}\]
  
  tmux send-keys -t work:0.3 '' C-m
  

  tmux select-layout -t work:0 bbfd,204x58,0,0\[204x34,0,0,0,204x23,0,35\{67x23,0,35,3,67x23,68,35,4,68x23,136,35,5\}\]

  tmux select-pane -t work:0.0

  # Window "servers"
  
  tmux send-keys -t work:1.0 '' C-m
  

  tmux splitw -t work:1
  tmux select-layout -t work:1 bbfd,204x58,0,0\[204x34,0,0,0,204x23,0,35\{67x23,0,35,3,67x23,68,35,4,68x23,136,35,5\}\]
  
  tmux send-keys -t work:1.1 '' C-m
  tmux send-keys -t work:1.1 mosh\ root@joeguilmette.com C-m

  tmux splitw -t work:1
  tmux select-layout -t work:1 bbfd,204x58,0,0\[204x34,0,0,0,204x23,0,35\{67x23,0,35,3,67x23,68,35,4,68x23,136,35,5\}\]
  
  tmux send-keys -t work:1.2 '' C-m
  tmux send-keys -t work:1.2 mosh\ joeguilm@joeguilmette.com C-m

  tmux splitw -t work:1
  tmux select-layout -t work:1 bbfd,204x58,0,0\[204x34,0,0,0,204x23,0,35\{67x23,0,35,3,67x23,68,35,4,68x23,136,35,5\}\]
  
  tmux send-keys -t work:1.3 '' C-m
  

  tmux select-layout -t work:1 bbfd,204x58,0,0\[204x34,0,0,0,204x23,0,35\{67x23,0,35,3,67x23,68,35,4,68x23,136,35,5\}\]

  tmux select-pane -t work:1.0

  # Window "vim"
  
  tmux send-keys -t work:2.0 '' C-m
  tmux send-keys -t work:2.0 vim C-m

  tmux splitw -t work:2
  tmux select-layout -t work:2 b7a6,204x58,0,0\{125x58,0,0,2,78x58,126,0\[78x28,126,0,9,78x29,126,29,10\]\}
  
  tmux send-keys -t work:2.1 '' C-m
  

  tmux splitw -t work:2
  tmux select-layout -t work:2 b7a6,204x58,0,0\{125x58,0,0,2,78x58,126,0\[78x28,126,0,9,78x29,126,29,10\]\}
  
  tmux send-keys -t work:2.2 '' C-m
  

  tmux select-layout -t work:2 b7a6,204x58,0,0\{125x58,0,0,2,78x58,126,0\[78x28,126,0,9,78x29,126,29,10\]\}

  tmux select-pane -t work:2.0

  tmux select-window -t 0
fi

if [ -z "$TMUX" ]; then
  tmux -u attach-session -t work
else
  tmux -u switch-client -t work
fi
```

Any ideas?
