### ISSUE TITLE
Pane with multiple commands requires name

### ISSUE THREAD

**Issue by Grazfather** [tmuxinator/tmuxinator#266]
If I create a window with multiple panes and then I want multiple commands to be run in one of the panes I need to assign a (useless) name.

This doesn't work:
```
name: test
root: ~/

windows:
  - editor:
      layout: main-vertical
      panes:
        -
          - cd tmp
          - vim testfile
        - guard
```

But this does:

```
name: test
root: ~/

windows:
  - editor:
      layout: main-vertical
      panes:
        - dumb:
          - cd tmp
          - vim testfile
        - guard
```

Though both are valid yaml.
