### ISSUE TITLE
"pre" option not using zsh options, alias, configuration (running as sh)

### ISSUE THREAD

**Issue by routeaccess** [tmuxinator/tmuxinator#286]
I'm trying to `pre` option to set a shell option, source a file, and run an alias to launch sublime text (defined under `Prezto` framework). (My default shell is `/bin/zsh` with `Prezto` shell framework)

Though `tmux` opens up, it doesn't execute the commands and I'm faced with the following error on exiting `tmux`:
```bash
> mux start auv-core
sh: 13: setopt: not found
sh: 13: source: not found
sh: 13: stt: not found
arranging in: main-vertical
arranging in: main-vertical
[exited]
```
Here is the `echo $SHELL` output to confirm I'm using `zsh`:
```bash
> echo $SHELL
/bin/zsh
```
My project configuration is as follows:
```yaml
# ~/.tmuxinator/auv-core.yml

name: auv-core
root: ~/

pre:
    - setopt clobber
    - source ~/projects/auv/devel/setup.zsh
    - stt

windows:
  - editor:
      layout: main-vertical
      panes:
        - vim
        - cd
```
where `setopt` is `zsh` for shell options, and `stt` is an alias to open Sublime Text as defined under Prezto.
