### ISSUE TITLE
Problem with custom layout

### ISSUE THREAD

**Issue by l0rda** [tmuxinator/tmuxinator#296]
```
# ~/.tmuxinator/stat.yml

name: stat
root: ~/
pre_window: cd ~

windows:
  - stats:
    - layout: 6c96,202x61,0,0{64x61,0,0[64x30,0,0{30x30,0,0,9,33x30,31,0,16},64x30,0,31,15],137x61,65,0,14}
    - panes:
      - vim
      - vim
      - vim
      - top
```

run: `mux start stat`

and got:
```
/usr/local/share/gems/gems/tmuxinator-0.6.11.pre/lib/tmuxinator/window.rb:44:in `block in build_commands': undefined method `shellescape' for #<Hash:0x00000001e90e70> (NoMethodError)
	from /usr/local/share/gems/gems/tmuxinator-0.6.11.pre/lib/tmuxinator/window.rb:43:in `map'
	from /usr/local/share/gems/gems/tmuxinator-0.6.11.pre/lib/tmuxinator/window.rb:43:in `build_commands'
	from /usr/local/share/gems/gems/tmuxinator-0.6.11.pre/lib/tmuxinator/window.rb:25:in `initialize'
	from /usr/local/share/gems/gems/tmuxinator-0.6.11.pre/lib/tmuxinator/project.rb:23:in `new'
	from /usr/local/share/gems/gems/tmuxinator-0.6.11.pre/lib/tmuxinator/project.rb:23:in `block in windows'
	from /usr/local/share/gems/gems/tmuxinator-0.6.11.pre/lib/tmuxinator/project.rb:22:in `map'
	from /usr/local/share/gems/gems/tmuxinator-0.6.11.pre/lib/tmuxinator/project.rb:22:in `with_index'
	from /usr/local/share/gems/gems/tmuxinator-0.6.11.pre/lib/tmuxinator/project.rb:22:in `windows'
	from /usr/local/share/gems/gems/tmuxinator-0.6.11.pre/lib/tmuxinator/project.rb:107:in `windows?'
	from /usr/local/share/gems/gems/tmuxinator-0.6.11.pre/lib/tmuxinator/config.rb:82:in `validate'
	from /usr/local/share/gems/gems/tmuxinator-0.6.11.pre/lib/tmuxinator/cli.rb:68:in `start'
	from /usr/local/share/gems/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/share/gems/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/share/gems/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/share/gems/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/local/share/gems/gems/tmuxinator-0.6.11.pre/bin/mux:18:in `<top (required)>'
	from /usr/local/bin/mux:23:in `load'
	from /usr/local/bin/mux:23:in `<main>'
```

Also, if use `main-vertical` layout and trying to start second tmux session:
```
# ~/.tmuxinator/z.yml

name: z
root: ~/

# Optional tmux socket
# socket_name: foo

# Runs before everything. Use it to start daemons etc.
# pre: sudo /etc/rc.d/mysqld start

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
# tmux_command: byobu

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
# startup_window: logs

windows:
  - editor:
      layout: main-vertical
      panes:
        - vim
        - ls
```
i got:
```
usage: new-session [-AdDP] [-F format] [-n window-name] [-s session-name] [-t target-session] [-x width] [-y height] [command]
session not found: z:0
session not found: z:0
usage: split-window [-dhvP] [-c start-directory] [-F format] [-p percentage|-l size] [-t target-pane] [command]
session not found: z:0
session not found: z:0
session not found: z:0
session not found: z:0
session not found: z:0
session not found: z
```

and tmux not started.

tmux 1.8
CentOS Linux release 7.0.1406 (Core)
tmuxinator-0.6.11.pre
same output on tmuxinator-0.6.10

mux doctor
```
Checking if tmux is installed ==> Yes
Checking if $EDITOR is set ==> Yes
Checking if $SHELL is set ==> Yes
```

**Comment by edi9999** [comment]
Using 0.6.9 version fixes it for me

**Comment by tlight** [comment]
try removing the leading '-' from 'layout' and 'panes'

example from the README.md: 
```
windows:
  - editor:
      layout: main-vertical
      panes:
        - vim
        - guard
  - server: bundle exec rails s
  - logs: tail -f log/development.log
```

to something like this:

```
# ~/.tmuxinator/stat.yml

name: stat
root: ~/
pre_window: cd ~

windows:
  - stats:
    layout: 6c96,202x61,0,0{64x61,0,0[64x30,0,0{30x30,0,0,9,33x30,31,0,16},64x30,0,31,15],137x61,65,0,14}
    panes:
      - vim
      - vim
      - vim
      - top
```
