### ISSUE TITLE
protocol version mismatch (client 8, server 6)

### ISSUE THREAD

**Issue by michidk** [tmuxinator/tmuxinator#308]
I'am using Debian Wheezy and just installed tmux & tmuxinator.
If i use this crontab: @reboot /usr/local/bin/mux start startup
(startup is my project name) and restart my server, attach to this session,
the following error appears:
```
protocol version mismatch (client 8, server 6)
```
Without this crontab Tmuxinator works just fine.

Some other odd behaviour is that if i create a new tmux window or logging into my server with ssh the following line appears:
-bash: /home/michidk/.bin/tmuxinator.bash: No such file or directory

like in this case:
Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
You have new mail.
Last login: Thu May 28 17:08:09 2015 from 95.91.236.115
-bash: /home/michidk/.bin/tmuxinator.bash: No such file or directory

My tmuxinator project:
```
# ~/.tmuxinator/startup.yml

name: startup
root: ../../home/michidk

windows:
  - TASKMNGR: htop
  - ProstBot: java -jar ProstBot-1.0-SNAPSHOT.jar
  - Sudo: sudo -i
  - bash: cd ~/
```

EDIT:
Just uninstalled tmux mainline, installed self compiled tmux (https://github.com/ThomasAdam/tmux with make). Now tmuxinator isn't even starting the project ("no sessions" if i execute tmux attach).
Didn't work with version 1.7 either.
