### ISSUE TITLE
`attach` and `post` options not honored?

### ISSUE THREAD

**Issue by yrammos** [tmuxinator/tmuxinator#310]
Using the following `mainmux.yml` file:

```
# ~/.tmuxinator/mainmux.yml
# you can make as many tabs as you wish...

name: mainmux
root: ~/Dropbox/Dissertation/avanti

attach: false

post: tmux -CC attach -t mainmux

windows:
  - Scratchpad: clear
  - LaTeX: clear
  - Git: tig
```

the `attach` and `post` commands do not yield the expected results (as I understand them based on a reading of the docs). In fact, `tmuxinator debug mainmux` run with and without these two commands produces exactly the same script, so they presently both appear to be dummy. Am I missing something?
