### ISSUE TITLE
Project names containing only numbers cause an error

### ISSUE THREAD

**Issue by rghamilton3** [tmuxinator/tmuxinator#313]
Here's the config that caused an issue:
``` 
# ~/.tmuxinator/1320.yml

name: 1320 
root: ~/

startup_window: Media

windows:
  - vim: vim 
  - Omega: 
        layout: d83f,149x103,0,0[149x51,0,0,7,149x51,0,52,10] 
        panes:
           - omega
           - #empty
  - Media: ncmpcpp
  - Personal: #empty 
```

and here's the error thrown:

```
/home/rghamilton3/.gem/ruby/2.2.0/gems/tmuxinator-0.6.11/lib/tmuxinator/project.rb:35:in `name': undefined method `shellescape' for 1320:Fixnum (NoMethodError)
    from /home/rghamilton3/.gem/ruby/2.2.0/gems/tmuxinator-0.6.11/lib/tmuxinator/window.rb:80:in `tmux_window_command_prefix'
    from /home/rghamilton3/.gem/ruby/2.2.0/gems/tmuxinator-0.6.11/lib/tmuxinator/window.rb:25:in `initialize'
    from /home/rghamilton3/.gem/ruby/2.2.0/gems/tmuxinator-0.6.11/lib/tmuxinator/project.rb:24:in `new'
    from /home/rghamilton3/.gem/ruby/2.2.0/gems/tmuxinator-0.6.11/lib/tmuxinator/project.rb:24:in `block in windows'
    from /home/rghamilton3/.gem/ruby/2.2.0/gems/tmuxinator-0.6.11/lib/tmuxinator/project.rb:23:in `map'
    from /home/rghamilton3/.gem/ruby/2.2.0/gems/tmuxinator-0.6.11/lib/tmuxinator/project.rb:23:in `with_index'
    from /home/rghamilton3/.gem/ruby/2.2.0/gems/tmuxinator-0.6.11/lib/tmuxinator/project.rb:23:in `windows'
    from /home/rghamilton3/.gem/ruby/2.2.0/gems/tmuxinator-0.6.11/lib/tmuxinator/project.rb:125:in `windows?'
    from /home/rghamilton3/.gem/ruby/2.2.0/gems/tmuxinator-0.6.11/lib/tmuxinator/config.rb:82:in `validate'
    from /home/rghamilton3/.gem/ruby/2.2.0/gems/tmuxinator-0.6.11/lib/tmuxinator/cli.rb:68:in `start'
    from /usr/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /usr/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /usr/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /usr/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /home/rghamilton3/.gem/ruby/2.2.0/gems/tmuxinator-0.6.11/bin/mux:18:in `<top (required)>'
    from /usr/bin/mux:23:in `load'
    from /usr/bin/mux:23:in `<main>'
```

Simply changing any arbitrary character to a letter results in no error and the config working as intended.  

System:
Arch Linux 
Bash 4.3.39
Zsh 5.0.8 (Confirmed in both)
tmux 2.0
mux 0.6.11
ruby 2.2.2p95
