### ISSUE TITLE
tmate compatability?

### ISSUE THREAD

**Issue by andyw8** [tmuxinator/tmuxinator#327]
Should tmuxinator be compatible with tmate? I've set 'tmux_command: tmate` but when running, it reports "failed to connect to server" (repeated several times).

**Comment by magicalbanana** [comment]
Is your tmux running prior to this?

**Comment by Fedalto** [comment]
I made it work with tmate specifying the socket file.

On your tmuxinator yml file:

```yaml
# Pass command line options to tmux. Useful for specifying a different tmux.conf.
tmux_options: -S /tmp/my-project-tmate-session

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
tmux_command: tmate
```
