### ISSUE TITLE
Common pre-panes command

### ISSUE THREAD

**Issue by hedgehog** [tmuxinator/tmuxinator#33]
heirachy of shared pre-panes command

```
tabs:
  - editor: 
      pre: echo 'I get run in each pane.  Before each pane command!'
      layout: main-vertical
      panes: 
        - vim
        - #empty, will just run plain bash
        - top
  - shell: git pull
  - guard:
      layout: tiled
      pre:
        - echo 'I get run in each pane.'
        - echo 'Before each pane command!'
      panes:
        -
        - #empty, will just run plain bash
        -
```
