### ISSUE TITLE
Support: Pane layout not started

### ISSUE THREAD

**Issue by schoeke** [tmuxinator/tmuxinator#330]
Hi,

I have the following line in my config:
windows:
  - irssi:
      layout: dcf4,146x32,0,0{123x32,0,0,22x32,124,0}
      panes:
        - irssi
        - cat .irssi/nicklistfifo

However, the setup is not started correctly.Irssi start, but no pane is created. I am looking for help to figure out what is going wrong. I couldn't find an irc channel which is why came here.

Any hint is appreciated.
Andrej

**Comment by podung** [comment]
Can you post your entire yaml config file, properly formatted in a code block?

**Comment by schoeke** [comment]
`windows:
  - irssi:
      layout: dcf4,146x32,0,0{123x32,0,0,22x32,124,0}
      panes:
        - irssi
        - cat .irssi/nicklistfifo
  - jackline: jackline
  - TaskWarrior: tasksh
  - Jrnl: #empty
  - TERM: #
  - TERM2: #`

**Comment by podung** [comment]
Hmm.  This doesn't appear to be the whole file.  Is it?  You also need a `name` node and a `windows` node.  When I do the following it seems to work.

```
name: irssi
windows:
  - irssi:
      layout: dcf4,146x32,0,0{123x32,0,0,22x32,124,0}
      panes:
        - irssi
        - cat .irssi/nicklistfifo
  - jackline: jackline
  - TaskWarrior: tasksh
  - Jrnl: #empty
  - TERM: #
  - TERM2: #
```

All the commands actually just throw exceptions on the command line because I don't have these files/applications, but it appears it should work fine.

Are you including a name/windows node?  If so, can you describe more specifically how the problem is manifesting itself?
