### ISSUE TITLE
Docker Machine pre_window command breaks pane commands

### ISSUE THREAD

**Issue by adambiggs** [tmuxinator/tmuxinator#332]
Docker Machine requires an init command to be run in each shell session, which I've set as the Tmuxinator `pre_window` command:

```yml
pre_window: eval "$(docker-machine env test-vm)"
```

This worked great at first, but a few weeks ago I noticed that any following pane commands don't work. Strangely, they're printed in the console but not evaluated.

E.g.:

```yml
pre_window: eval "$(docker-machine env test-vm)"

windows:
  - "Test":
    panes:
      - ls
```

When I launch the above config, I get the following output:

```
$ eval "$(docker-machine env test-vm)"
ls
$
```

**Comment by magicalbanana** [comment]
Can you get a full trace?

**Comment by geowa4** [comment]
I can also confirm this is happening. I just switched one of my projects from boot2docker to docker-machine. If I switch back to boot2docker, it works even though the command fails. `echo $?` returns 0 when using this eval statement so I don't believe that's the issue.

**Comment by geowa4** [comment]
Changing to the following also fails the same way. It runs the eval statement, but no more.

```
windows:
    - work:
        root: /path/to/project
        panes:
            - main:
                - eval "$(docker-machine env dev)"
                - workon myenv
```
