### ISSUE TITLE
Can't run the first window tab

### ISSUE THREAD

**Issue by jerrygb** [tmuxinator/tmuxinator#342]
Using tmuxinator 0.6.11 and tmux 2.0

tmux show-window-option -g pane-base-index
pane-base-index 1

tmux show-option -g base-index       
base-index 1

Seems to be the same issue as that of https://github.com/tmuxinator/tmuxinator/issues/126

Could you please point me in the right direction?

Thanks.

**Comment by jerrygb** [comment]
Seems we can get over this issue if we have sleep on the shell for first window. For instance

```yaml
windows:                                                                                                                                                                          
  - manager:                                                                                                                                                                      
    - sleep 3                                                                                                                                                                     
    - manager-vm                                                                                                                                                                  
    - C-l        
```
