### ISSUE TITLE
how to use the  'args[n]'

### ISSUE THREAD

**Issue by Zonzely** [tmuxinator/tmuxinator#352]
hello!
my yml file is following.
```
# ~/.tmuxinator/coding.yml

name: coding
root: ~/<%= @args[0] %>

# Optional tmux socket
# socket_name: foo

# Runs before everything. Use it to start daemons etc.
# pre: sudo /etc/rc.d/mysqld start

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
# tmux_command: byobu

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
# startup_window: logs

# Controls whether the tmux session should be attached to automatically. Defaults to true.
# attach: false

# Runs after everything. Use it to attach to tmux with custom options etc.
# post: tmux -CC attach -t coding

windows:
  - editor:
      layout: 381c,213x57,0,0[213x48,0,0,4,213x8,0,49,5]
      panes:
        - vim
        - 
```

when i start the project,it tell me  *"Failed to parse config file. Please check your formatting."*
