### ISSUE TITLE
tmuxinator does not execute .tmux.conf

### ISSUE THREAD

**Issue by gon1332** [tmuxinator/tmuxinator#366]
I use `tmuxinator 0.7.1`. When I open the project, I can see that my tmux settings from ~/.tmux.conf have not loaded (as they should(?) by default).

My tmuxinator .yaml is this:
```
# ~/.tmuxinator/development.yml

name: devproject
root: ~/devproject

windows:
  - editor:
      layout: main-horizontal
      panes:
        - vim
        - #empty, will just run plain zsh
  - console: # empty
```

And the `mux debug [projectname]` emits:
```
#!/bin/zsh

# Clear rbenv variables before starting tmux
unset RBENV_VERSION
unset RBENV_DIR

tmux start-server\; has-session -t devproject 2>/dev/null

if [ "$?" -eq 1 ]; then
  cd /home/gon1332/devproject

  # Run pre command.
  

  # Create the session and the first window. Manually switch to root
  # directory if required to support tmux < 1.9
  TMUX= tmux new-session -d -s devproject -n editor
  tmux send-keys -t devproject:1 cd\ /home/gon1332/devproject C-m


  # Create other windows.
  tmux new-window  -t devproject:2 -n console


  # Window "editor"
  tmux send-keys -t devproject:1.1 vim C-m

  tmux splitw -c /home/gon1332/devproject -t devproject:1
  tmux select-layout -t devproject:1 main-horizontal
  

  tmux select-layout -t devproject:1 main-horizontal

  tmux select-pane -t devproject:1.1

  # Window "console"

  tmux select-window -t 1
fi

  if [ -z "$TMUX" ]; then
    tmux -u attach-session -t devproject
  else
    tmux -u switch-client -t devproject
  fi
```

where I do not see something like `source tmux.conf`.
My .tmux.conf has these permissions: `-rw-rw-r--` or `664`.

Is there a solution to this problem?
