### ISSUE TITLE
Create pane failed when using custom layouts

### ISSUE THREAD

**Issue by DanielArndt** [tmuxinator/tmuxinator#374]
It seems a bug was introduced with the method used in PR #48. Now, there are create pane failed issues with custom layouts (likely because they are expecting a discrete amount of panes, unlike the built-ins which expect any number of panes).

```
arranging in: d8e3,264x77,0,0[264x54,0,0,3,264x22,0,55{132x22,0,55,4,131x22,133,55,6}]
create pane failed: pane too small
arranging in: d8e3,264x77,0,0[264x54,0,0,3,264x22,0,55{132x22,0,55,4,131x22,133,55,6}]
arranging in: d8e3,264x77,0,0[264x54,0,0,3,264x22,0,55{132x22,0,55,4,131x22,133,55,6}]
arranging in: d8e3,264x77,0,0[264x54,0,0,3,264x22,0,55{132x22,0,55,4,131x22,133,55,6}]
create pane failed: pane too small
arranging in: d8e3,264x77,0,0[264x54,0,0,3,264x22,0,55{132x22,0,55,4,131x22,133,55,6}]
arranging in: d8e3,264x77,0,0[264x54,0,0,3,264x22,0,55{132x22,0,55,4,131x22,133,55,6}]
```
My yml:

```
name: docker                                                                                                                                                                                                                                                           
root: ~/                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                       
windows:                                                                                                                                                                                                                                                               
  - docker:                                                                                                                                                                                                                                                            
      layout: d8e3,264x77,0,0[264x54,0,0,3,264x22,0,55{132x22,0,55,4,131x22,133,55,6}]                                                                                                                                                                                 
      panes:                                                                                                                                                                                                                                                           
        - #                                                                                                                                                                                                                                                            
        - #empty                                                                                                                                                                                                                                                       
        - #empty       
```
Debug gives the following:
```
$  mux debug develop                                                                                                                                                                                                                                                   
#!/bin/zsh

# Clear rbenv variables before starting tmux
unset RBENV_VERSION
unset RBENV_DIR

tmux start-server\; has-session = develop 2>/dev/null

if [ "$?" -eq 1 ]; then
  cd /home/darndt

  # Run pre command.
  

  # Create the session and the first window. Manually switch to root
  # directory if required to support tmux < 1.9
  TMUX= tmux new-session -d -s develop -n are-platform
  tmux send-keys -t develop:0 cd\ /home/darndt/repo/git/are-platform C-m


  # Create other windows.
  tmux new-window -c /home/darndt/repo/git/ARE.jl -t develop:1 -n ARE-jl


  # Window "are-platform"
  tmux send-keys -t develop:0.0 vim C-m

  tmux splitw -c /home/darndt/repo/git/are-platform -t develop:0
  tmux select-layout -t develop:0 d8e3,264x77,0,0\[264x54,0,0,3,264x22,0,55\{132x22,0,55,4,131x22,133,55,6\}\]
  tmux send-keys -t develop:0.1 julia C-m

  tmux splitw -c /home/darndt/repo/git/are-platform -t develop:0
  tmux select-layout -t develop:0 d8e3,264x77,0,0\[264x54,0,0,3,264x22,0,55\{132x22,0,55,4,131x22,133,55,6\}\]
  

  tmux select-layout -t develop:0 d8e3,264x77,0,0\[264x54,0,0,3,264x22,0,55\{132x22,0,55,4,131x22,133,55,6\}\]

  tmux select-pane -t develop:0.0

  # Window "ARE-jl"
  tmux send-keys -t develop:1.0 vim C-m

  tmux splitw -c /home/darndt/repo/git/ARE.jl -t develop:1
  tmux select-layout -t develop:1 d8e3,264x77,0,0\[264x54,0,0,3,264x22,0,55\{132x22,0,55,4,131x22,133,55,6\}\]
  tmux send-keys -t develop:1.1 julia C-m

  tmux splitw -c /home/darndt/repo/git/ARE.jl -t develop:1
  tmux select-layout -t develop:1 d8e3,264x77,0,0\[264x54,0,0,3,264x22,0,55\{132x22,0,55,4,131x22,133,55,6\}\]
  

  tmux select-layout -t develop:1 d8e3,264x77,0,0\[264x54,0,0,3,264x22,0,55\{132x22,0,55,4,131x22,133,55,6\}\]

  tmux select-pane -t develop:1.0

  tmux select-window -t 0
fi

  if [ -z "$TMUX" ]; then
    tmux -u attach-session -t develop
  else
    tmux -u switch-client -t develop
  fi

```
Reverting #48 fixes the issue, but would obviously re-introduce the issue with tiled layouts.

Possibly related is #351
