### ISSUE TITLE
Problem with nesting / undefined method `shellescape'

### ISSUE THREAD

**Issue by AlexZeitler** [tmuxinator/tmuxinator#379]
When I try to run this custom layout

```yml
windows:
  - editor:
      layout: main-vertical
      panes:
        - left:
            layout: main-horizontal
            panes:
              - dockercompose:
                - cd ~/src/integration
                - nodemon -w .. -e js,json,html -x "docker-compose kill && docker-compose up -d"
              - input:
                - bash
        - right:
            panes:       
            - gruntjobs
              - cd ~/src/ui
              - grunt watch
```

I get this error:

```bash
/var/lib/gems/1.9.1/gems/tmuxinator-0.7.1/lib/tmuxinator/pane.rb:38:in `tmux_main_command': undefined method `shellescape' for ["layout", "main-horizontal"]:Array (NoMethodError)
	from (erubis:54:in `block (3 levels) in render'
	from (erubis:53:in `each'
	from (erubis:53:in `block (2 levels) in render'
	from (erubis:45:in `each'
	from (erubis:45:in `block in render'
	from (erubis:34:in `each'
	from (erubis:34:in `render'
	from /var/lib/gems/1.9.1/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `eval'
	from /var/lib/gems/1.9.1/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `result'
	from /var/lib/gems/1.9.1/gems/tmuxinator-0.7.1/lib/tmuxinator/project.rb:81:in `render'
	from /var/lib/gems/1.9.1/gems/tmuxinator-0.7.1/lib/tmuxinator/cli.rb:124:in `render_project'
	from /var/lib/gems/1.9.1/gems/tmuxinator-0.7.1/lib/tmuxinator/cli.rb:144:in `start'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /var/lib/gems/1.9.1/gems/tmuxinator-0.7.1/bin/mux:15:in `<top (required)>'
	from /usr/local/bin/mux:23:in `load'
	from /usr/local/bin/mux:23:in `<main>'
```

**Comment by AlexZeitler** [comment]
I was using it totally wrong

```yml
windows:
  - editor:
      layout: 1fd2,205x62,0,0{102x62,0,0[102x21,0,0,16,102x40,0,22,18],102x62,103,0,17}
      panes:
        - dockercompose
            - cd ~/src/integration
            - nodemon -w .. -e js,json,html -x "docker-compose kill && docker-compose up -d"
        - input:
            - bash
        - gruntjobs:
            - cd ~/src/ui
            - grunt watch
```

First, create the desired layout using tmux.
Then detach the session.
Then ```tmux list-windows```:
```
0: editor* (3 panes) [205x62] [layout 87ff,205x62,0,0{102x62,0,0[102x21,0,0,0,102x40,0,22,1],102x62,103,0,2}] @0 (active)
```

Then grab the content inside the brackets starting with "layout" and paste it as ```layout:``` to the tmuxinator file.
