### ISSUE TITLE
Strange behaviour when panes defined as multi-element dictionaries

### ISSUE THREAD

**Issue by podung** [tmuxinator/tmuxinator#406]
There appears to be a bug in the handling of a pane element that contains a multi-element dictionary.  I found it when working on a PR for #266.

```yaml
# This works: A pane with 2 elements in an array, each being a single-element dictionary
panes:
  - pane1: echo "first pane"
  - pane2: echo "second pane"
# results in the expected 2 panes, each running its respective echo command.
```

```yaml
# This doesn't: An array that contains a multi-element dictionary
panes:
  - pane1: echo "first pane"
    pane2: echo "second pane"
# bizarrely creates three panes
# All the commands run in the first pane, the next two panes are empty panes
```

The options I see are:
1. Take the first element and ignore the rest (this is consistent with how multi-element Windows yaml is handled (`value = window_yaml.values.first` in window.rb:18)
2. Make each element its own pane
3. Print out some sort of invalid format error

I know its a corner case that's pretty minor, but I'm trying clean up the surrounding code a bit while I address #266.

Any thoughts?  I'm open to any suggestions.
