### ISSUE TITLE
Resolve window/root relative to project root

### ISSUE THREAD

**Issue by rmccue** [tmuxinator/tmuxinator#410]
If you have multiple windows with differing roots (#283), you have to specify an absolute path for all windows. This can lead to your .conf looking like:

```
name: example
root: ~/Work/Projects/Example

windows:
  - vagrant:
      root: ~/Work/Projects/Example
      panes:
        - vagrant status
  - frontend:
      root: ~/Work/Projects/Example/frontend
      panes:
        -
  - frontend-build:
      root: ~/Work/Projects/Example/frontend
      panes:
        - grunt
  - app:
      root: ~/Work/Projects/Example/app
      panes:
        -
```

This involves a bunch of path duplication. Unfortunately, relative paths are resolved relative to the working dir of tmuxinator, which makes usage unreliable. Instead, it'd be great to have this resolve relative to the project root instead.
