### ISSUE TITLE
Configurable tmuxinator

### ISSUE THREAD

**Issue by hedgehog** [tmuxinator/tmuxinator#42]
In issue #41 I mentioned progressing tmuxinator towards easily allowing power configurations - essentially as a step toward having snippets/aliases that abstract those details.  To do this we need to expose tmux's option setting.  If issue #41 is pulled in here is what the next step might look like (note the use of syntax consistent with tmux, i.e. `-` in place of `_` giving consistency in the tmux option names and tmuxinator option names - yes this would require a 0.x release :)

`layout` `keys` and `notifications` would all be common/convenient/best-practice config snippets that are distirbuted with tmuxinator and inserted as called, e.g. `keys: emacs`, these of course could be global as well as tab specific.

```
# ~/.tmuxinator/<%= @name %>.yml
# you can make as many tabs as you wish...

project-name: Tmuxinator
project-root: ~/code/rails_project
socket-name: foo    # Not needed.  Remove to use default socket
rbenv: "1.9.2-p290"
bundler: on         # optional bundler rbenv-plugin
pre: sudo /etc/rc.d/mysqld start
server-options:
  - opt-name-1: value 1 # See
  - opt-name-2: val2
session-options:
  - opt-name-1: value 1
  - opt-name-2: val2
window-options:
  - opt-name-1: value 1
  - opt-name-2: val2
environment:
  - ENV_VAR_A: value1
tabs:
  - editor:
      environment:
        - ENV_VAR_A: value2
        - ENV_VAR_B: value1
      window-options:
        - opt-name-1: value 1
        - opt-name-2: val2
      session-options:
        - opt-name-1: value 1
        - opt-name-2: val2
      layout: main-vertical
      panes:
        - vim
        - #empty, will just run plain bash
        - top
  - shell: git pull
      layout: tmuxinator_display_name
      keys: tmuxinator_binding_name
      notifications: tmuxinator_notice_name
  - database: rails db
  - server: rails s
  - logs: tail -f logs/development.log
  - console: rails c
  - capistrano:
  - server: ssh me@myhost
```

thoughts?
