### ISSUE TITLE
Equal sign parsing for arguments

### ISSUE THREAD

**Issue by svigneux** [tmuxinator/tmuxinator#430]
Hi,
I'm looking to use tmuxinator to use a single .yml file to launch commands against a pre-defined list of hosts.  

If no argument is given when starting tmux, I just get shell access. If I'm passing a command, then it runs and I can capture the output. So far so good!  

```
➜ tmuxinator version  
tmuxinator 0.8.1
➜ ruby --version      
ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]
```
Using this yml file
```
# ~/.tmuxinator/prod.yml

name: prod
root: ~/

startup_window: app

windows:
  - infra:
      layout: tiled
      panes:
        - ssh -tt host1.infra '<%= @settings["command"] %>'
        - ssh -tt host2.infra '<%= @settings["command"] %>'
  - app:
      layout: tiled
      panes:
        - ssh -tt host1.app '<%= @settings["command"] %>'
        - ssh -tt host2.app '<%= @settings["command"] %>'
        - ssh -tt host3.app '<%= @settings["command"] %>'
  - db:
      layout: tiled
      panes:
        - ssh -tt host1.db '<%= @settings["command"] %>'
  - net:
      layout: tiled
      panes:
        - ssh -tt host1.net '<%= @settings["command"] %>'
```
Starting tmuxinator with a simple command works: 
`tmux start prod command='sudo apt-get update'`
But if the command contains `=` signs, the command gets truncated: 

`mux start fnct command='sudo DEBIAN_FRONTEND="noninteractive" apt-get update -y'`
Only `sudo DEBIAN_FRONTEND` is sent. 

I tracked the issue to line 42 of file [lib/project.rb](https://github.com/tmuxinator/tmuxinator/blob/master/lib/tmuxinator/project.rb) 

```
    def self.parse_settings(args)
      # puts args
      settings = args.select { |x| x.match(/.*=.*/) }
      args.reject! { |x| x.match(/.*=.*/) }

      settings.map! do |setting|
        parts = setting.split("=")
        [parts[0], parts[1]]
      end
```

By echoing args, the quoting seem stripped to:  
`command="sudo DEBIAN_FRONTEND=noninteractive apt-get update -y"`

Is this something that would be merged if fixed? 
Could a regex lord show me a way to match quoted and unquoted strings? Let me know if I can help

Thanks
