### ISSUE TITLE
Tmuxinator doesn't run commands in tmux windows

### ISSUE THREAD

**Issue by yatishb** [tmuxinator/tmuxinator#466]
I'm running tmux 2.2. I know this isn't the recommended version with this package but I'd love it if I could use this to script my tmux session. I'm looking to open a few windows and panes and have them run some commands. However, no matter what I change, the commands aren't executed and I just end up getting the different windows and panes.

Here's my yml file:
```
# ~/.tmuxinator/docker.yml
name: docker
root: ~/docker
windows:
  - dev:
      layout: main-vertical
      panes:
        - vim
        - docker:
          - cd /work/dev/
          - git status
  - logs: tail -f /logs/dev.log
```

The commands just seem to get printed on the window screen and not executed.
