### ISSUE TITLE
default values for @settings params

### ISSUE THREAD

**Issue by Ghardo** [tmuxinator/tmuxinator#468]
Hello,

how can i easy define default values for params?

the only what i found is a little bit overhead
`# ~/.tmuxinator/test_default_params.yml

name: test_default_params
root: ~/

windows:
  - editor:
      layout: main-vertical
      panes:
        - (\[ "<%= @settings["a"] %>"  == "" \] && echo "a not set" || echo "a is set")
        - (\[ "<%= @settings["b"] %>"  == "" \] && echo "b not set" || echo "b is set")`

**Comment by mohkale** [comment]
Yes, this would be an extremely useful feature.

```yaml
name: foo
root: ~/

# default settings go here
settings:
  my_config_dir: ~/.config/foo
  my_cache_dir: ~/.local/share/foo

windows:
  editor:
    panes:
      - vim <%= @settings["my_config_dir"] %>
```

I'm not sure whether we should allow erb in the settings object above (it'll depend on when settings are assigned I suppose, are command line settings present before config file settings?)

**Comment by mohkale** [comment]
Looks like settings are parsed in [project.rb](https://github.com/tmuxinator/tmuxinator/blob/master/lib/tmuxinator/project.rb#L46) from the command line options. However I can't see any good way to implement this (which I presume is why it hasn't been implemented yet).

We need to assign the settings before we pass our config through erb and then parse the YAML, but we need to parse the yaml to assign the defaults for the settings :/. So the only approach I can think of would involve parsing the YAML twice, which is suboptimal to say the least.

**Comment by noahfrederick** [comment]
> how can i easy define default values for params?

The most straightforward way is:

```yaml
name: example
root: ~/

windows:
  - editor:
      panes:
        - echo <%= @settings["foo"] || "default" %>
```

If you don't want to specify the default value inline (for example, if you need to reference the setting in more than one place), you can already accomplish something along the lines of what @mohkale was suggesting with a little ERB:

```yaml
name: example
root: ~/

<%
  # Defaults for settings go here.
  @settings["foo"] ||= "~/.config/foo"
  @settings["bar"] ||= "~/.local/share/foo"
%>

windows:
  - editor:
      panes:
        - echo <%= @settings["foo"] %>
        - echo <%= @settings["bar"] %>
```
