### ISSUE TITLE
Can not create more than two panes in a window. It results in parse error.

### ISSUE THREAD

**Issue by aashudwivedi** [tmuxinator/tmuxinator#478]
I am not able to create a window with more than two panes. 

only adding a new pane to the default configuration results in a error saying : `Failed to parse config file. Please check your formatting.`

Here is my config file : 

```
name: test
root: ~/
windows:
  - editor:
      layout: main-vertical
      panes:
        - vim
        - guard
        - ls
  - server: bundle exec rails s
  - logs: tail -f log/development.log
```
