### ISSUE TITLE
Cannot Find Pane and commands not running

### ISSUE THREAD

**Issue by brandonsturgeon** [tmuxinator/tmuxinator#481]
I know this issue has been posted a thousand times, but I've tried as many things as I saw I could.  Please let it be something dumb :/

Here's my tmuxinator yml file

```
# ~/.tmuxinator/stat.yml                                                                                                                                                                                          

name: stat
root: ~/

windows:
  - stat:
      layout: 79dd,210x47,0,0{105x47,0,0,55,104x47,106,0[104x23,106,0,56,104x23,106,24{52x23,106,24,57,51x23,159,24,58}]}
      panes:
        - echo 'test1'
        - echo 'test2'
        - echo 'test3'
        - echo 'test4'

```

Here's the output after I exit all tmux windows (which by the way, are formatted properly, it's just that no commands are being run)

```
brandon@brandon-VirtualBox:~$ tmuxinator start stat
can't find pane 1
can't find pane 2
can't find pane 3
can't find pane 4
```

My `echo` commands are not being run in the panes, but the panes are being opened properly.

Here's my `tmux show-options -g`

```
brandon@brandon-VirtualBox:~$ tmux show-options -g
assume-paste-time 1
base-index 1
bell-action any
bell-on-alert off
default-command ""
default-shell "/bin/bash"
destroy-unattached off
detach-on-destroy on
display-panes-active-colour red
display-panes-colour blue
display-panes-time 1000
display-time 750
history-limit 10000
lock-after-time 0
lock-command "lock -np"
message-command-style fg=yellow,bg=black
message-style fg=black,bg=yellow
mouse on
mouse-utf8 on
prefix C-a
prefix2 <NONE>
renumber-windows off
repeat-time 500
set-remain-on-exit off
set-titles on
set-titles-string "#S:#I:#W - "#T" #{session_alerts}"
status on
status-interval 60
status-justify left
status-keys vi
status-left "#[fg=green](#S) #(whoami)"
status-left-length 30
status-left-style default
status-position bottom
status-right "#[fg=yellow]#(cut -d " " -f 1-3 /proc/loadavg)#[default] #[fg=white]%H:%M#[default]"
status-right-length 40
status-right-style default
status-style fg=white,bg=black
status-utf8 on
update-environment "DISPLAY SSH_ASKPASS SSH_AUTH_SOCK SSH_AGENT_PID SSH_CONNECTION WINDOWID XAUTHORITY"
visual-activity on
visual-bell off
visual-silence off
word-separators " -_@"
```

You'll notice that `pane-base-index 1` isn't present, but here's an excerpt from my `.tmux.conf`

```
 set-option -g base-index 1
 set-option -g pane-base-index 1
 set -g pane-base-index 1
 set-window-option -g pane-base-index 1

```

So I'm not sure what's going on with that.

And here's my debug:

```
brandon@brandon-VirtualBox:~$ tmuxinator debug stat
#!/bin/bash

# Clear rbenv variables before starting tmux
unset RBENV_VERSION
unset RBENV_DIR

tmux start-server;

  cd /home/brandon

  # Run pre command.


  # Create the session and the first window. Manually switch to root
  # directory if required to support tmux < 1.9
  TMUX= tmux new-session -d -s stat -n stat
  tmux send-keys -t stat:1 cd\ /home/brandon C-m


  # Create other windows.


  # Window "stat"
  tmux send-keys -t stat:1.1 echo\ \'test1\' C-m

  tmux splitw -c /home/brandon -t stat:1
  tmux select-layout -t stat:1 tiled
  tmux send-keys -t stat:1.2 echo\ \'test2\' C-m

  tmux splitw -c /home/brandon -t stat:1
  tmux select-layout -t stat:1 tiled
  tmux send-keys -t stat:1.3 echo\ \'test3\' C-m

  tmux splitw -c /home/brandon -t stat:1
  tmux select-layout -t stat:1 tiled
  tmux send-keys -t stat:1.4 echo\ \'test4\' C-m

  tmux select-layout -t stat:1 tiled

  tmux select-layout -t stat:1 79dd,210x47,0,0\{105x47,0,0,55,104x47,106,0\[104x23,106,0,56,104x23,106,24\{52x23,106,24,57,51x23,159,24,58\}\]\}
  tmux select-pane -t stat:1.1


  tmux select-window -t 1
  tmux select-pane -t 0

  if [ -z "$TMUX" ]; then
    tmux -u attach-session -t stat
  else
    tmux -u switch-client -t stat
  fi
```
### Some other notes
- I've tried messing with indentation. A lot.
- I've tried all different spellings and variations of `pane-base-index` option and all of that.
- I've tried putting the commands in strings, tried other commands with no strings, etc.

Is there anything else I can provide? Is there an easy solution?
