### ISSUE TITLE
Can't find pane 0

### ISSUE THREAD

**Issue by Shamaoke** [tmuxinator/tmuxinator#485]
After starting a session I get a `can't find pane 0` [message](https://youtu.be/tnv0LzaI4Os) in the console. I don't observe any other issues then the message: windows and panes are created, and programs are started. I think the bug is related to the fact I change `base-index` and `pane-base-index` to `1`, since when I remove the settings, the message doesn't appear.

Linux (Arch); tmux 2.3; tmuxinator 0.9.0; [configuration files](https://gist.github.com/Shamaoke/db76b4419c1d43b897d588a73caa19ac)

**Comment by seriley** [comment]
I get the same error. When I do **mux debug sample** I note that one of the last commands in the output is **tmux select-pane -t 0**. tmuxinator doesn't appear to recognize the pane-base-index setting in .tmux.conf

**Comment by Soliah** [comment]
Make sure you restart your tmux server (or just stop all sessions).

**Comment by dcalhoun** [comment]
I experience this as well using the following in my `tmux.conf`.

```
set -g base-index 1
set-window-option -g pane-base-index 1
```

**Comment by zx1986** [comment]
In my Mac, this not work:
```
set -g base-index 1
set-option -g base-index 1
set-window-option -g pane-base-index 1

set -g status-right '#{prefix_highlight} | %a %Y-%m-%d %H:%M'
set-option -g default-command "reattach-to-user-namespace -l zsh"
```

**Comment by zx1986** [comment]
https://github.com/tmuxinator/tmuxinator/issues/137

**Comment by akuma** [comment]
+1

**Comment by wassimk** [comment]
I have the same issue as @akuma except I also tried HEAD and same problem. I have @zx1986 config and it doesn't help.

**Comment by zx1986** [comment]
@wassimk yes, I said 'not work' too.

**Comment by Heuristack** [comment]
Hi, same here, macOS; tmux 2.3; tmuxinator 0.9.0

**Comment by ctnieves** [comment]
Same issue here. 
tmuxinator 0.9.0
macOS 10.12

**Comment by muellerj** [comment]
+1. The first pane of the first window gets the `cd ~/root/path/of/the/project`, all other panes and windows start in the wrong dir (from where `tmuxinator` was called).

    Cygwin x86 2.8.0
    tmuxinator 0.9.0
    tmux 2.0

**Comment by kevinquillen** [comment]
Same issue as the other mac users, and I too have base-index set.

**Comment by cyrossignol** [comment]
Just ran into this issue as well. In my particular case, I needed to format my project's yml file properly. It seems as if the yaml parser is pretty strict about spacing, but I didn't see any formatting errors. I also needed to set the `startup_pane` directive to `1`. I've been getting around the issue described by @muellerj by manually `cd`ing in each pane/window:

```yml
name: example
startup_pane: 1

windows:
  - one
      layout: main-vertical
      panes:
        - cd "<%= @args[0] %>" && actual-command 
        - cd "<%= @args[0] %>" && actual-command
```

```
mux start example "$(pwd)"
```

or even..

```
alias dev='mux start example "$(pwd)"'
```

**Comment by craighurley** [comment]
Adding `startup_pane: 1` removed the error for me.  Thanks for the tip @cyrossignol.

`~/.tmux.conf` looks has the following:
```
set-option -g base-index 1
set-window-option -g pane-base-index 1
```

`~/.tmuxinator/test.yml` looks like:
```
name: test
root: ~/tmp/
startup_pane: 1

windows:
  - testing:
      root: ~/Projects/testing/
      layout: main-horizontal
      panes:
        -
        -
  - ansible:
      root: ~/Projects/ansible/
      layout: main-horizontal
      panes:
        -
        -
```

I'm running `macOS 10.12.5` with the following versions:
```
$ tmux -V
tmux 2.5

$ gem list | grep tmuxinator
tmuxinator (0.9.0)
```
