### ISSUE TITLE
Having trouble getting this working...

### ISSUE THREAD

**Issue by agibralter** [tmuxinator/tmuxinator#5]
Here is my yml:

```
# ~/.tmuxinator/foo.yml
# you can make as many tabs as you wish...

project_name: Foo
project_root: /projects/foo
rvm: ree
tabs:
  - main:
      layout: main-vertical
      panes:
        -
        -
        -
        -
  - log: tail -f log/development.log
```

This is the output I get in my terminal (once I exit my mangled tmux session):

```
failed to connect to server: Connection refused
set option: base-index -> 1
window not found: Foo:1
window not found: Foo:1
window not found: Foo:1
window not found: Foo:1
window not found: Foo:1
window not found: Foo:1
window not found: Foo:1
window not found: Foo:1
window not found: Foo:1
```

Any thoughts?
