### ISSUE TITLE
Escaping issue with colon-space

### ISSUE THREAD

**Issue by mlsteele** [tmuxinator/tmuxinator#515]
When a pane has a command like this `- echo "a: b"` it doesn't work. The pane ends up executing only part of the command. I think that the problem is the colon-space combined with some escaping. You can tell from the output of `tmuxinator debug` that something is wrong.

What follows is a simple example. Where this really bit me was in a useful command with `| grep -E "some: stuff"`.

```
# ~/.tmuxinator/bug.yml

name: bug
root: ~/

windows:
  - main:
      layout: main-vertical
      panes:
          - echo good
          - echo "a: b"
```

`tmuxinator bug`:
![image](https://cloud.githubusercontent.com/assets/705646/24057349/7956b2bc-0b1d-11e7-9269-a991eb22c5a7.png)

```
$ tmuxinator debug bug
#!/bin/zsh

# Clear rbenv variables before starting tmux
unset RBENV_VERSION
unset RBENV_DIR

tmux start-server;

  cd /Users/miles

  # Run pre command.
  

  # Create the session and the first window. Manually switch to root
  # directory if required to support tmux < 1.9
  TMUX= tmux new-session -d -s bug -n main
  tmux send-keys -t bug:0 cd\ /Users/miles C-m


  # Create other windows.


  # Window "main"
  tmux send-keys -t bug:0.0 echo\ good C-m

  tmux splitw -c /Users/miles -t bug:0
  tmux select-layout -t bug:0 tiled
  tmux send-keys -t bug:0.1 b\" C-m  #<-- here you can see that everything before `b` has been lost.

  tmux select-layout -t bug:0 tiled

  tmux select-layout -t bug:0 main-vertical
  tmux select-pane -t bug:0.0


  tmux select-window -t 0
  tmux select-pane -t 0

  if [ -z "$TMUX" ]; then
    tmux -u attach-session -t bug
  else
    tmux -u switch-client -t bug
  fi
```

In `bug.yaml`, changing `echo "a: b"` to `echo "a:\ b"` kind of works in that it dodges the bug, but then it ends up echoing a slash which isn't the intent of the command.

Versions:
```
tmuxinator 0.9.0
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
rbenv 1.0.0
zsh 5.2 (x86_64-apple-darwin15.4.0)
macOS 10.12.3 (16D32)
```

**Comment by anquegi** [comment]
I also have the same problem with the following tmuxinator file, in this case is for executing smalltalk code in a remote gnu smalltalk environment:

```
# ~/.tmuxinator/st.yml
name: st
root: ~/learn/gnu-smalltalk
attach: false

# Runs before everything. Use it to start daemons etc.
on_project_start:
  - emacs --daemon=gst --title=GST
  - export EDITOR="emacsclient --server-file=gst -c -n"
  - export VISUAL=$EDITOR
  - $EDITOR &;
  - gst-load -iI shampoo.im Shampoo
  - gst-remote -I shampoo.im --daemon
  - gst-remote -e "Shampoo.ShampooServer startOn: 9090 login: 'st' pass: 'st'"

on_project_exit:
  - tmux -CC attach -t st

windows:
  - console-emacs-dev:
      - export EDITOR="emacsclient --server-file=gst -c -n"
      - export VISUAL=$EDITOR      
      - echo "A currar"
  - exercism:
      - export EDITOR="emacsclient --server-file=gst -c -n"
      - export VISUAL=$EDITOR
```

**Comment by anquegi** [comment]
Hi @mlsteele I find that this is a problem for yaml syntax, I found the solution with [this](https://interviewbubble.com/solved-how-to-escape-indicator-characters-or-in-yaml-escaping-colons-in-yaml/):

> Plain scalars(value field) must never contain the “: ” and “ #” character combinations. Such combinations would cause ambiguity with mapping key: value pairs and comments.
> 
> In addition, inside flow collections, or when used as implicit keys, plain scalars must not contain the “[”,  “]”,  “{”,  “}”  and “,” characters. These characters would cause ambiguity with flow collection structures.
> 
> You can try these options:
> 
> YAML
> 
> - url: 'http://www.example-site.com/'
> - url: "http://www.example-site.com/"
> - url:
>     http://www.example-site.com/
> - url: >-
>     http://www.example-site.com/ #Recommended
> - url: |-
>     http://www.example-site.com/ #Recommended

so for your bug.yaml file you can use:

```
# ~/.tmuxinator/bug.yml

name: bug
root: ~/

windows:
  - main:
      - echo good
      - >-
        echo "a: b"
```

Only a for the curious, because depending on the execution context of the string it should work or no, I suppose like this [issue](https://github.com/ansible/ansible/issues/2769), this works for echo but not for smalltalk, which is my case:

```
# ~/.tmuxinator/bug.yml

name: bug
root: ~/

windows:
  - main:
      - echo good
      - >-
        echo "a:\u0020b"
```

![Captura de pantalla 2019-05-02 a las 12 47 05 (2)](https://user-images.githubusercontent.com/2518346/57070864-017a3500-6cd9-11e9-9713-05989ba46cb2.png)

In my case I did change to this and finally worked:

```
# ~/.tmuxinator/st.yaml
name: st
root: ~/learn/gnu-smalltalk
attach: false

# Runs before everything. Use it to start daemons etc.
on_project_start:
  - emacs --daemon=gst --title=GST
  - export EDITOR="emacsclient --server-file=gst -c -n"
  - export VISUAL=$EDITOR
  - $EDITOR
  - gst-load -iI shampoo.im Shampoo
  - gst-remote -V -I shampoo.im --daemon
  - >-
    gst-remote -V -e "Shampoo.ShampooServer startOn: 9092 login: 'toni' pass: 'toni'."

on_project_exit:
  - tmux -CC attach -t st

windows:
  - console-emacs-dev:
      - export EDITOR="emacsclient --server-file=gst -c -n"
      - export VISUAL=$EDITOR      
      - echo "A currar"
  - exercism:
      - export EDITOR="emacsclient --server-file=gst -c -n"
      - export VISUAL=$EDITOR
```
 So I think that this issue must be closed
