### ISSUE TITLE
Display issue when opening Vim with splits

### ISSUE THREAD

**Issue by kleinjm** [tmuxinator/tmuxinator#532]
Display issue
![image](https://cloud.githubusercontent.com/assets/2565158/26382663/dd9be7a2-3ffb-11e7-9072-a4861dfb6997.png)

My config
```
# ~/.tmuxinator/dotfiles.yml

name: dotfiles
root: ~/GitHubRepos/dotfiles

windows:
  - editor:
      layout: e571,272x59,0,0[272x49,0,0,24,272x9,0,50,25]
      # Synchronize all panes of this window, can be enabled before or after the pane commands run.
      # 'before' represents legacy functionality and will be deprecated in a future release, in favour of 'after'
      # synchronize: after
      panes:
        - vim -O ~/.vimrc ~/.tmux.conf ~/.zshrc
        -
```
I tried [this suggestion](https://stackoverflow.com/a/18056690/2418828) with no luck.
