### ISSUE TITLE
Project config, command not found: undle

### ISSUE THREAD

**Issue by jordancalder** [tmuxinator/tmuxinator#535]
In my project.yml file, I have the following configuration:

```
windows:
   - editor:
       layout: main-vertical
       panes:
         - $EDITOR .
         - bundle exec rails s -p 3000
         - npm start
```
The first command in the panes works fine and opens my project in vim. The other panes try to run the commands `undle exec rails s -p 3000` and `pm start`, respectively.
