### ISSUE TITLE
Wrong window selected on startup, startup_window not working

### ISSUE THREAD

**Issue by NicolasWebDev** [tmuxinator/tmuxinator#537]
By default, the startup_window should be the first one.

When starting the session, it is always the last window that is selected (in this case, server).

startup_window does not have any effect.

I am using:
tmux 2.5-1
tmuxinator 0.9.0-1
archlinux

Below is my configuration, in case it may be useful.
```
# ~/.tmuxinator/blog.yml

name: blog
root: ~/work/projects/nicolaswebdev_blog

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
startup_window: 1

windows:
  - editor: vim
  - extra1:
  - extra2:
  - server: bundle exec jekyll liveserve --drafts
```
