### ISSUE TITLE
[Feature request]Possibility to set options per window

### ISSUE THREAD

**Issue by LoveIsGrief** [tmuxinator/tmuxinator#546]
Hi,

First of all, thanks for the software 👍 It's been pretty helpful!

It would be nice to have the possibility to do something like this

```yaml
windows:
   - group1:
      options:  #<------
         - monitor-activity on
         - force-width 81
         - @myCustomVar karma
```

So running `set-window-option` for the given window.

If this is already possible in some other way, please do point me in the direction.

Cheers

**Comment by LoveIsGrief** [comment]
Nevermind, solution is 

```yaml
windows:
   - group1:
      panes:
         - tmux set-window-option monitor-activity on
         - tmux set-window-option force-width 81
         - tmux set-window-option @myCustomVar karma
```

It'll be in the correct session and window, so it's all good.

Cheers
