### ISSUE TITLE
'on_project_stop' hook with docker-compose

### ISSUE THREAD

**Issue by iovis9** [tmuxinator/tmuxinator#555]
I'm trying the following to start/stop my docker-compose configuration:
```yaml
name: some_site
root: ~/Sites/some_site

on_project_first_start: docker-compose up -d
on_project_stop: docker-compose stop

windows:
  - editor: $EDITOR -S ~/.dotfiles/.vim/sessions/some_site.vim
```

`on_project_first_start` works as expected, launches the docker-compose configuration nicely! But when I stop the tmux session (tried exiting all terminals inside, running `:kill-session` and killing the session when detached) the docker server is still running. I don't know how to debug this or when is this hook supposed to run.

**Comment by ethagnawl** [comment]
Hey, @iovis9.

It looks like this hook is only run when you use the `tmuxinator stop some_site` command. (This feature needs better documentation and I'll open a separate issue for that.)

However, I was just reviewing the pull request this feature came in on and I mentioned that I'd had trouble with that command on my system (Debian 8/9) back then. Are you running Linux, too?

**Comment by iovis9** [comment]
I'm running the latest macOS. I just tried `tmuxinator stop some_site` with the following:
1. Detaching first and then running the command: working
2. Running the command from the actual session: kills the session correctly but doesn't fire up the hook

**Comment by ethagnawl** [comment]
Ping @endorama. 

Do you have any idea what's going on here? Is this the expected behavior?

**Comment by endorama** [comment]
Hello! I'm on holiday right now and I can't debug it properly, sorry. I'll
have a better look next week when I'm back!
>
>
For what I remember, this is not expected to work just killing tmux,
because of tmuxinator behaviour: the `on_stop` hook is run when the command
`tmuxinator stop` is run, not when the tmux session/server is killed.

Also, running tmuxinator stop from inside tmux will probably not work as
the tmux session ( and the shell within ) is killed before running the
`on_stop` command ( look at lib/tmuxinator/assets/template-stop.erb ).

As tmuxinator just create and run a shell script for performing it's
actions, to debug it's behaviour you can print on screen the command before
it's execution ( temporary hacking a bit the source code of the gem ).

The expected behaviour is: run the command after killing the tmux session.

I remember reading about tmux hook that could be used for this, but I was
not proficient enough to do it. If someone could help, I'll gladly have a
look again.

@ethagnawl if you want to assign the documentation PR to me highlighting
what need clarification I'll submit a PR.

@iovis9 if you still need help let me get back from holidays and I'll help
you. I currently use with success the `tmuxinator stop <project>` command,
so should be a viable workaround.

**Comment by endorama** [comment]
@iovis9 I'm back! Do you still need help?

**Comment by iovis9** [comment]
Sorry for the silence! Knowing how it works inside I just started to detach and then running `tmuxinator stop` to kill the session, so I think we're good unless we want to actually support the feature of running the command from the session.

**Comment by beaugunderson** [comment]
noting that `post:` (now deprecated) does work with `:kill-session` from inside the session but that `on_project_stop` and `on_project_exit` do not; this breaks my workflow.

**Comment by endorama** [comment]
@beaugunderson I'd say that this is not the expected behaviour.

Please have a look at lines [96 to 99 in the template file](https://github.com/tmuxinator/tmuxinator/blob/e3f3210ff6a3f31a99dab58385d7f138fd45c997/lib/tmuxinator/assets/template.erb#L96-L99):

```erb
<%= post %>
<%- unless attach? -%>
  # Run on_project_exit command.
<%= hook_on_project_exit %>
<%- end -%>
````

`on_project_exit` should behave as `post`, I have added by purpose of maintaining backward compatibility. Is possible that the `unless attach?` check is breaking this behaviour.

Could you please open a new issue with a more complete example and use case for me to look at? Thanks

**Comment by codezomb** [comment]
I would definitely like to put my thoughts in here. previous `post` functionality is missing, and definitely breaks our workflow. In my opinion it would make sense that `on_project_exit` did this.

**Comment by endorama** [comment]
Hi @codezomb, could you help me in understanding the use case?

With the previous implementation, the `post` was effectively running on detach from the tmux session. This has been replaced by the `on_project_exit` ( which could be an example of poor naming, but should retain the same behaviour ). If not is a bug, and I suspect the `unless attach?` check is to blame.

The `on_project_stop` is called *only* when `tmuxinator stop project` is run, so I don't think is helpful for this particular use case.

If you help me in understanding the use case I'm willing to work on this to help you retaining your workflow :slightly_smiling_face: The different hook were meant to be an enhancement, not a loss of functionality.

Adding a reference to the PR that introduced the change, to add a bit of context https://github.com/tmuxinator/tmuxinator/pull/486

Thanks!

**Comment by codezomb** [comment]
@endorama yeah, for sure. I originally misunderstood post, and did not realize it also closed on detach. However, `on_project_exit` does not seem to execute on kill-session or detach as post did before (at least for me). I've tried both `on_project_start` and `on_project_exit` with no luck.

The use case I guess I'm asking for is a new one that runs on tmuxinator stop AND kill-session. Take the following configuration from into account:

```yaml
name: my_awesome_workflow
root: .

on_project_first_start: docker-compose up -d
on_project_stop:
  - rm -rf /tmp/{folder1, folder2}
  - <other clean up command>
  - docker-compose stop
```

This is super useful in that when you kill the session everything you started stopped, and folders that were created can be cleaned up. This puts you back into a perfect position to restart the project again. However, it is not useful for when you detach, because everything is still running.

I manage dev spaces for a team, and giving them a single command to run to get started is amazing, until you realize that they have to manually clean up after themselves, or remember to run a separate clean up command (tmuxinator stop).

Hopefully this is helpful.

**Comment by beaugunderson** [comment]
agreed, my use case is the same as Mike’s :)

---

**Comment by endorama** [comment]
:slightly_frowning_face: weird, I tried starting the project and running `tmux kill-session -t test` from inside the session and the output is this:

```
my-shell $ tmuxinator start test
tmux-session $ tmux kill-session -t test
[exited]
on_project_exit
no server running on /tmp/tmux-1000/default
on_project_stop
my-shell $
```

What is the tmuxinator version?

**Comment by beaugunderson** [comment]
if it makes a difference, i am executing kill session via `ctrl-a :kill-session` (would be `ctrl-b :kill-session` with default keybindings)

**Comment by beaugunderson** [comment]
it also does not work if i issue `tmux kill-session` from within a shell inside the session though... i wonder why it works for you and not for me?

i'm using tmux 2.7 and tmuxinator 0.11.1 from `brew` on macOS 10.13.4

**Comment by beaugunderson** [comment]
here's my whole file in case it's useful:

```yaml
name: home-app

# set the iTerm 2 tab color to Canvas orange
on_project_start:
  - printf "\033]6;1;bg;red;brightness;240\a"
  - printf "\033]6;1;bg;green;brightness;116\a"
  - printf "\033]6;1;bg;blue;brightness;82\a"
  - docker network create messaging &> /dev/null
  - docker network create mock-lab-engine &> /dev/null
  - docker network create ontologies &> /dev/null
  - docker network create pharmacy &> /dev/null
  - docker network create science &> /dev/null
  - docker network create web-to-pdf &> /dev/null

# set the iTerm 2 tab color back to the default (currently broken)
on_project_exit:
  - echo on_project_exit
  - printf "\033]6;1;bg;*;default\a"
on_project_stop:
  - echo on_project_stop
  - printf "\033]6;1;bg;*;default\a"

windows:
  - primary:
      layout: main-vertical
      panes:
        - docker-compose up --build web
        - yarn && yarn build_dev
        - yarn test --watch
  - secondary:
      layout: tiled
      panes:
        - cd ../messaging && docker-compose up --build web
        - cd ../pharmacy && docker-compose up --build web
        - cd ../science && docker-compose up --build web
        - cd ../web-to-pdf && docker-compose up --build web
```
