### ISSUE TITLE
tmuxinator 0.9.0-2 panels render in wrong place / size

### ISSUE THREAD

**Issue by mrturtledev** [tmuxinator/tmuxinator#557]
When using tmux/tmuxinator I can't get the tmuxinator windows to load in the correct place at the correct size. I ran tmux and configured the panels how I wanted them, detached and ran tmux list-windows -t 0 to get the layout. I copied the relevant bit of the layout to a tmuxinator config called recon, but they are out of position when starting that tmuxinator profile.

Kali rolling
tmux                                      2.6~rc3-1                            amd64        
tmuxinator                                0.9.0-2                              all          

list-windows 0: bash* (4 panes) [317x85] [layout 2fb3,317x85,0,0{203x85,0,0[203x21,0,0{97x21,0,0,0,105x21,98,0,4},203x63,0,22,3],113x85,204,0,1}] @0 (active)

list-windows   recon* (4 panes) [317x85] [layout 87e8,317x85,0,0{196x85,0,0[196x33,0,0{121x33,0,0,9,74x33,122,0,10},196x51,0,34,11],120x85,197,0,12}] @2 (active)

layout from  tmuxinator config                 2fb3,317x85,0,0{203x85,0,0[203x21,0,0{97x21,0,0,0,105x21,98,0,4},203x63,0,22,3],113x85,204,0,1}

The layout from the recon config matches the layout from list-windows -t 0 where I "templated" it from. However the list-windows -t recon after running tmuxinator start recon, shows a different value.

Here is the recon profile
# ~/.tmuxinator/recon.yml

```
name: recon
root: ~/

windows:
   recon:
      layout: 2fb3,317x85,0,0{203x85,0,0[203x21,0,0{97x21,0,0,0,105x21,98,0,4},203x63,0,22,3],113x85,204,0,1}
      root: /usr/src/git/
      panes:
        - screenfetch
        - date
        - cd ./WhatWeb/ && reset
        - date
```

This is all done in the same SSH session, same size window, etc.
