### ISSUE TITLE
Only first window in each project appears

### ISSUE THREAD

**Issue by rightaway** [tmuxinator/tmuxinator#570]
With my config as follows (using tmux `master` and tmuxinator `0.9.0`), only `window1` appears, no other windows. This happens in various tmuxinator projects I have. This happened after upgrading from tmux `2.6` to `master` in order to fix a related issue https://github.com/tmux/tmux/issues/1146.

```
name: something
windows:
  - window1:
      root: ~/some/path1
      panes: command1
  - window2:
      root: ~/some/path2
      panes: command2
```
