### ISSUE TITLE
pre_window doesn't execute

### ISSUE THREAD

**Issue by Krakob** [tmuxinator/tmuxinator#571]
Trying to set up a project, but I'm having trouble getting pre_window commands to run, which I'm using for virtual environments. It seems to just skip that. The DB window never tries to start mysql and the ones with pipenv don't seem to try to start that.

Tmuxinator config:
```
name: myproject
root: ~/Git/myproject/

windows:
  - Editor:
      pre_window: pipenv shell
      layout: main-vertical
      panes:
        - Vim:
          - nvim .
        - Log:
          - tail -f devlog.txt
        - Shell:
          - #zsh

  - Shell:
      pre_window: pipenv shell
      layout: main-vertical
      panes:
        - #zsh
        - #zsh

  - DB:
      pre_window: sudo /etc/init.d/mysql start
      layout: even-vertical
      panes:
        - Serverlogin:
          - mycli -u devlogin -p devpass -D myproject
        - Me:
          - mycli -S /var/run/mysqld/mysqld.sock -D myproject

  - Server:
      pre_window: pipenv shell
      panes:
        - FLASK_APP=src/myproject.py flask run |& tee devlog.txt

  - Mux:
    - tmuxinator open myproject
```

`mux debug myproject` output:
```

#!/bin/zsh

# Clear rbenv variables before starting tmux
unset RBENV_VERSION
unset RBENV_DIR

tmux start-server;

cd /home/jakob/Git/myproject

# Run on_project_start command.


  # Run on_project_restart command.
  

  if [ -z "$TMUX" ]; then
    tmux -u attach-session -t myproject
  else
    tmux -u switch-client -t myproject
  fi
```

**Comment by rglassett** [comment]
@Krakob after some testing, it looks like your `pre_window` setting needs to be at the top level of your `project.yml`. The same `pre_window` command will run for all of your windows/panes (i.e., it's not specific to a single window).

From your example, if you want to run `pipenv shell` for only your Workspace window, you could do that like so:

```yml
windows:
  - Editor:
      layout: main-vertical
      panes:
        - Vim:
          - pipenv shell && nvim .
        - Log:
          - pipenv shell && tail -f devlog.txt
        - Shell:
          - pipenv shell #zsh
```

Depending on how common this use case is, I think it would be reasonable to make a feature request for `pre` hooks to be scoped such that they run for each pane in a window, or each window in a project.
