### ISSUE TITLE
Starting project opens 7 new lxterminal instances, does not cd to root

### ISSUE THREAD

**Issue by tripl3dogdare** [tmuxinator/tmuxinator#585]
This problem just started popping up today. Whenever I run `tmuxinator start bots`, it successfully starts in the same window, but does not sudo to the `root` I set in the project config and opens 7 extra terminal instances all running the same tmux instance. This results in a considerable amount of desktop clutter, as well as all but the first pane (which seems to cd into root fine for some reason) to fail with "no such directory" errors. I've triple-checked that all my paths are right, as well.

Computer: Raspberry Pi 3 Model B
OS: Raspbian (latest)
Ruby version: 2.3.3p222
tmuxinator version: latest (updated today)

`bots.yml`

```yml
# ~/.tmuxinator/bots.yml

name: bots
root: ~/Bots

windows:
  - bots:
      layout: tiled
      panes:
        - cd Nepcore/nepnep && npm start
        - cd RuneBot && npm start
        - cd TsunBot && npm start
        - cd Sibyl && bundle exec ruby sibyl.rb
        - cd 'Ruby Bot' && bundle exec ruby main.rb
        - cd yui && bundle exec ruby yui.rb
  - terminal: 
```
