### ISSUE TITLE
Window initialization commands are reissued during attach when using socket_name option

### ISSUE THREAD

**Issue by signe** [tmuxinator/tmuxinator#594]
tmuxinator 0.10.1
tmux 2.6

Problem:
When re-attaching to a session that's already running, if the socket_name option is defined the window startup commands are reissued to the window, possibly causing issues to running processes/etc.

Expected:
Initialization shouldn't be sent.  Commenting the socket_name option reverts to the expected behavior.

Configuration:
```
name: test
root: ~/

# Optional tmux socket
socket_name: foo

windows:
  - echo: echo 'foobar'
  - echo2: echo 'bazbar'
```

Output from session 0 (start session, two newlines added by me, detach, reattach):

```
cd /home/signe
echo 'foobar'
$ cd /home/signe
$ echo 'foobar'
foobar
$
$
$ cd /home/signe
$ echo 'foobar'
foobar
```
