### ISSUE TITLE
How to change the zoom state of a panel ?

### ISSUE THREAD

**Issue by marcelpaulo** [tmuxinator/tmuxinator#616]
I've just installed tmuxinator d81a2fcd8d469e67b1838845caf8dcc48b57164c on Xubuntu 18.04 with tmux/tmux@645fe901, and I can't find out how to create a pane with the zoom state toggled.

My config is way too simplistic, it wouldn't even merit using tmuxinator, but I wanted to try it out, and eventually grow to more complex setups:

```yaml
startup_window: bash
windows:
  - mc: mc
  - bash:
      layout: even-horizontal
      panes:
        -
        -
```

What I want is: to toggle the zoom state of the first pane in window `bash` (which I'd do running `tmux resize-pane -Z`). Up to now I was accomplishing this using this bash script:

```bash
#!/bin/bash

# already attached to a session
[[ $TMUX ]] && exit

if ! tmux has-session -t default; then
    tmux new-session -s default -n mc -d -- mc
    tmux new-window -t default -n bash
    tmux split-window -t default -h
    tmux select-pane -t default -l
    tmux resize-pane -t default -Z
fi

exec tmux attach-session -t default
```

I guess the more generic question would be: how to modify window/pane properties after they're created ? I wasn't sure which issue title would best reflect what I need.

**Comment by ethagnawl** [comment]
Hi, @marcelpaulo. 

Apologies for the delayed response, but you could achieve the above using: 

```
name: _foo
windows:
  - one:
      panes:
        - tmux resize-pane -Z && echo left1 # this window/pane will receive focus and then be "zoomed" into
        - echo right1
```

For anyone seeing this in the future who is looking to do something slightly more complicated, like selecting the second window's second pane, you could do something like:

```
name: _foo
startup_window: 1
startup_pane: 1
windows:
  - one:
      panes:
        - echo left1
        - echo right1
  - two:
      panes:
        - echo left2
        - tmux resize-pane -Z && echo right2 # this window/pane will receive focus and then be "zoomed" into
```

I'm not sure this use case is common enough to add a config option for it, but I'd be interested in hearing from anyone who does think it'd be worthwhile.
