### ISSUE TITLE
Layout option / panes not being sent through to tmux

### ISSUE THREAD

**Issue by JonRowe** [tmuxinator/tmuxinator#629]
Using the latest version of tmuxinator `0.11.2`, panes and layout for a window doesn't do anything, project file:

```
project_name: td
project_root: ~/Code/TheProject/Dashboard
windows:
  - editor: vim
  - shell:
    layout: main-vertical
    panes:
      - git status
      - yarn run
```

Output:
```
#!/bin/bash

# Clear rbenv variables before starting tmux
unset RBENV_VERSION
unset RBENV_DIR

tmux start-server;

cd /Users/jon/Code/TheProject/Dashboard

# Run on_project_start command.


  # Run on_project_restart command.
  

  if [ -z "$TMUX" ]; then
    tmux -u attach-session -t td
  else
    tmux -u switch-client -t td
  fi


    
# Run on_project_exit command.
```
