### ISSUE TITLE
Allow use of conditionals

### ISSUE THREAD

**Issue by onhernandes** [tmuxinator/tmuxinator#638]
I've a config file which works for both back-end and front-end development. But when I'm working only with back-end, I start a window for another front-end app which won't be used, so I've to close it manually.

Since tmuxinator allows use of arguments and options, I think that could have a "toogle" value/option/arg for creating some window or not. Like: 

```
windows:
  - work:
      root: /var/www/wip/
      layout: main-horizontal
      panes:
        - nvim
        - DEBUG=mongoose npm run mon
  - app-v2: 
      enable: <%= @args[0] %> == "app-v2"
      root: /var/www/app-v2
      panes:
        - nvim
        - yarn start
```

IDK how this could be achieved.

**Comment by ethagnawl** [comment]
Hey, @onhernandes. 

What you're after can already be achieved using ERB conditionals, like:

```
name: foo
root: ~/

windows:
  - one:
      layout: main-vertical
      panes:
        - echo one
  <%- if args[0] == "app-v2" %>
  - two:
      layout: main-vertical
      panes:
        - echo two
  <%- end %>
```
