### ISSUE TITLE
Allow/use YAML references in config file

### ISSUE THREAD

**Issue by adamstrickland** [tmuxinator/tmuxinator#643]
```yaml
name: hack
root: ~/src

x-editor: &editor
  root: ~/src/hellblazer
  layout: main-vertical
  panes:
    - vim
    - ;
    - ;

windows:
  - one:
      <<: *editor
```

Throws an error `Filed to parse config file: Unknwon alias: editor`.  Defining `&editor` inline does the same, e.g.

```yaml
name: hack
root: ~/src

x-editor: &editor
  root: ~/src/hellblazer
  layout: main-vertical
  panes:
    - vim
    - ;
    - ;

windows:
  - one:&editor
      root: ~/src/hellblazer
      layout: main-vertical
      panes:
        - vim
        - ;
        - ;
  - two:
      <<: *editor
```

This (or some similar, `ref`-based config DRYing) should work.
