### ISSUE TITLE
Force terminal dimensoins

### ISSUE THREAD

**Issue by sabrehagen** [tmuxinator/tmuxinator#647]
Hi,

I'm running `tmuxinator` in a docker container and would like `stty cols 63 rows 271` to run before `tmuxinator` so that I can force a certain session dimension. Are project hooks the appropriate way to do this? Alternatively, can session dimensions be set through the `tmuxinator` config, not inherited from the terminal?

**Comment by ethagnawl** [comment]
Hi, @sabrehagen.

Yes, you should be able to achieve what you're after using the `on_project_start` hook.

Something like this: 

```
name: dims
on_project_start: stty cols 63 rows 271
windows:
  - one:
      layout: main-vertical
      panes:
        - echo hello
```

If you regularly detach/attach from sessions, you may also need to use the `on_project_restart` hook.
