### ISSUE TITLE
Custom layout not created correctly.

### ISSUE THREAD

**Issue by andho** [tmuxinator/tmuxinator#651]
I created a tmux layout and got this using list-windows:
`0: bash* (4 panes) [282x71] [layout b6b8,282x71,0,0{141x71,0,0,3,140x71,142,0[140x35,142,0{70x35,142,0,5,69x35,213,0,7},140x35,142,36,6]}] @2 (active)`

Then I put this in my config file:

```
name: project1                                                                                          
root: ~/dev/projects/project1/apps/backend
windows:                                                                                            
   - editor:                                                                                         
       layout: b6b8,282x71,0,0{141x71,0,0,3,140x71,142,0[140x35,142,0{70x35,142,0,5,69x35,213,0,7},140x35,142,36,6]}
       # Synchronize all panes of this window, can be enabled before or after the pane commands run. 
       # 'before' represents legacy functionality and will be deprecated in a future release, in favour of 'after'
       # synchronize: after                                                                          
       panes:                                                                                        
         - vim                                                                                       
         -                                                                                           
         - task                                                                                      
         - 

```
Now when I start the project, the top-right most pane is much smaller then the original layout. So I used tmuxinator debug to get the code and tried the line that sets the layout:

`tmux select-layout -t project1:0 b6b8,282x71,0,0\{141x71,0,0,3,140x71,142,0\[140x35,142,0\{70x35,142,0,5,69x35,213,0,7\},140x35,142,36,6\]\}`

This fixes the layout.

This is on Ubuntu:18.04. Let me know any other info that might be needed.

**Comment by andho** [comment]
OS: Ubuntu 18.04.1 LTS
Kernel: 4.15.0-33-generic
Ruby: 2.5.1p57

Output of gem list:
```
*** LOCAL GEMS ***

bigdecimal (default: 1.3.4)
cmath (default: 1.0.0)
csv (default: 1.0.0)
date (default: 1.0.0)
dbm (default: 1.0.0)
did_you_mean (1.2.0)
erubis (2.7.0)
etc (default: 1.0.0)
fcntl (default: 1.0.0)
fiddle (default: 1.0.0)
fileutils (default: 1.0.2)
gdbm (default: 2.0.0)
io-console (default: 0.4.6)
ipaddr (default: 1.2.0)
json (default: 2.1.0)
minitest (5.10.3)
net-telnet (0.1.1)
openssl (default: 2.1.0)
power_assert (0.2.7)
psych (default: 3.0.2)
rake (12.3.1)
rdoc (default: 6.0.1)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
stringio (default: 0.0.1)
strscan (default: 1.0.0)
test-unit (3.2.5)
thor (0.19.4)
tmuxinator (0.8.1)
webrick (default: 1.4.2)
zlib (default: 1.0.0)

```

**Comment by JamesB41** [comment]
I'm experiencing the exact same issue, fwiw.

**Comment by nastynaz** [comment]
Also having this issue.

**Comment by qbantek** [comment]
Same issue. Ubuntu 18.04

Temporary hack:
```yml
name: project                                                                      
root: ~/projects/project                                                 
                                                                                  
windows:                                                                         
  - editor:                                                                      
    layout: e414,317x86,0,0[317x63,0,0,0,317x22,0,64,2]               
    panes:                                                                     
      - $EDITOR                                                                
      - tmux select-layout -t embed:0 e414,317x86,0,0\[317x63,0,0,0,317x22,0,64,2\] && 
        clear
```

**Comment by emarthinsen** [comment]
I'm experiencing the same issue. The temporary hack works, but it's ugly. Here's my config, without the hack:

```
windows:
  - editor:
      layout: d37c,380x66,0,0{142x66,0,0,0,237x66,143,0,4}
      panes:
        - guard
        - vim
  - console: #just zsh
  - server: bundle exec rails s
  - logs: tail -f log/development.log
```

The layout definitely isn't being applied.

**Comment by XobSod** [comment]
Same problem here:
```
windows:
  - Server:
      layout: 28e2,239x67,0,0{146x67,0,0[146x31,0,0,0,146x35,0,32,1],92x67,147,0[92x15,147,0{38x15,147,0,2,53x15,186,0,3},92x19,147,16,4,92x31,147,36,5]}
      panes:
        - 
        - 
        - 
        - 
        - 
        - 
```

Upper right panes are restored wrongly.

**Comment by ethagnawl** [comment]
I just had a quick look at this and it seems to be a result of tmux trying to apply that layout to the session before it's been rendered. 

I'll have to chew on it to figure out what the best approach is (possibly using a hook in the generated script/commands ...) but for now, a slightly less dirty hack than creating a bogus pane to handle the layout selection would be to use a project hook. I just tested the following using @andho's config and it seems to work consistently, but YMMV:

```
name: project1
on_project_start: $(sleep 1 && tmux select-layout -t project1:0 b6b8,282x71,0,0\{141x71,0,0,3,140x71,142,0\[140x35,142,0\{70x35,142,0,5,69x35,213,0,7\},140x35,142,36,6\]\}) &
windows:
   - editor:
       layout: b6b8,282x71,0,0{141x71,0,0,3,140x71,142,0[140x35,142,0{70x35,142,0,5,69x35,213,0,7},140x35,142,36,6]}
       # Synchronize all panes of this window, can be enabled before or after the pane commands run.
       # 'before' represents legacy functionality and will be deprecated in a future release, in favour of 'after'
       # synchronize: after
       panes:
         - echo 1
         - echo 2
         - echo 3
         - echo 4
```
