### ISSUE TITLE
Conditionally show a Window

### ISSUE THREAD

**Issue by sabrehagen** [tmuxinator/tmuxinator#658]
**Is your feature request related to a problem? Please describe.**
I use tmuxinator to monitor 20 microservices in my stack, one window per microservice. In production mode, all services are running and each window displays the desired output. In development mode, only a subset of the 20 microservices are running (often as little as 3), leaving many empty windows that I must navigate sequentially through to get to the logs of the next running microservice.

**Describe the solution you'd like**
I'd like to be able to disable certain windows based on the result of a command. I'll illustrate my idea with a new `when: condition` property. If `when` is absent, the default value is `always`. If `when` is present, the window will be shown if evaluating `condition` returns true, and the window will be hidden if evaluating `condition` returns false.

Example configuration

```yml
windows:
  - pipeline-containers:
      when: ps a | grep pipeline-server
      layout: even-vertical
      panes:
        - yarn docker:ctop:pipelines
        - yarn docker:logs:pipelines:containers
  - api-server:
      when: ps a | grep api-server
      layout: even-vertical
      panes:
        - yarn docker:ctop:api
        - yarn docker:logs:api
```

**Describe alternatives you've considered**
I make config files that are subsets of the full config. This is far less convenient for my purposes than having all windows in one config file.

**Additional context**
Scrolling through 17 of these dead screens is frustrating.
![tmuxinator](https://user-images.githubusercontent.com/1094600/47979241-1bfe9780-e116-11e8-9823-bfbf71ab673a.png)

**Comment by ethagnawl** [comment]
Hi, @sabrehagen.

This is worthy of consideration.

In the meantime, you should be able to achieve what you're after using ERB in your project`s configuration file.

Here's an example from #638:

```
name: foo
root: ~/
windows:
  - one:
      layout: main-vertical
      panes:
        - echo one
  <%- if args[0] == "production" %>
  - two:
      layout: main-vertical
      panes:
        - echo two
  <%- end %>
```

You'd then start your project using `tmuxinator start foo` or `tmuxinator start foo production`.
