### ISSUE TITLE
Can't send <F1> as a command

### ISSUE THREAD

**Issue by jsatk** [tmuxinator/tmuxinator#667]
A snippet from my tmuxinator config yml.

```yml
windows:
  - "📧":
      panes:
        - mail:
          - mutt
          - <F1> # I have no idea how to get this to work
          - O # Syncs mail
```
`<F1>` here is parsed as if I am literally pressing those four characters in sequence. This makes sense! But after reading through the README a few times and digging through the issues I still can't figure out if it's possible to send that second command as if I was literally pressing the F1 button.
