### ISSUE TITLE
Tmuxinator repeats the initialization commands on attach

### ISSUE THREAD

**Issue by urbainvaes** [tmuxinator/tmuxinator#719]
**Describe the bug**
Tmuxinator correctly sends keys to a tmux window upon creation of the session. However, subsequent calls of `tmuxinator SESSION` not only attaches to the running session but also resends the keys. This seems to happen only when `tmux_options` are included.

**To Reproduce**
Use this configuration:

```yaml
# ~/.tmuxinator/test.yml

name: test
root: ~/

tmux_options: -L test

windows:
  - test_window:
      - echo $(date)
```
then type
```bash
tmuxinator test
```
detach from session and type again
```bash
tmuxinator test
```

**Expected behavior**
The second call of `tmuxinator test` should not send `echo $(date)`.

**Environment**
 - tmuxinator Version: 1.1.1
 - tmux Version: 2.9a
 - Ruby Version: 2.6.4p104
 - OS: Archlinux
