### ISSUE TITLE
tmuxinator crashes tmux and causes graphical issues with two fullscreen apps

### ISSUE THREAD

**Issue by chrisjohnson** [tmuxinator/tmuxinator#721]
**Describe the bug**
Graphical glitches and sometimes tmux crashes

**To Reproduce**
I've got a tmuxinator config defined very simply as

```yaml
name: test
root: ~/helm-charts

windows:
  - editor:
      layout: main-horizontal
      panes:
        - # Shell
        - # Shell
```

When I run a full-screen app (such as running less in pager mode, or vim) in the top pane, and then run a full-screen app in the bottom pane, it starts screwing things up graphically:

![image](https://user-images.githubusercontent.com/178144/65619000-57ec5680-df8d-11e9-8430-1babd9819ecf.png)

If I run a `cat` in the second pane and the contents are larger than what would fit into the pane, the whole tmux server crashes:

```
[lost server]
```

**Expected behavior**
No graphical glitches or crashes.

I'm able to repeat these same steps in vanilla tmux and it works just fine there

**Environment**
 - tmuxinator Version: tmuxinator 1.1.0`
- tmux Version: `tmux 2.9a`
 - Ruby Version: `ruby 2.4.6p354 (2019-04-01 revision 67394) [x86_64-darwin16]`
 - OS: `macOS mojave`
 - iTerm: `Build 3.3.3beta2`
