### ISSUE TITLE
ERB does not evaluate no matter what I try

### ISSUE THREAD

**Issue by martinvelos** [tmuxinator/tmuxinator#731]
**Describe the bug**
After not being able to insert the @args[0], I tried whatever to track the problem, this is the minimal project:
```
# ~/.tmuxinator/playground.yml
name: playground
root: ~/
windows:
  - content:
      layout: vertical
      panes:
        #- echo $varr; echo <%= settings["par"] %> 
        - echo $varr; echo <%= args[0] %>
        - bash --version
```
and when I run it, with a parameter or not, I get:  
```
$ tmuxinator start playground paraaam
Failed to parse config file. Please check your formatting.
```

**Expected behavior**
A more guiding message with what to fix or where the problem was detected.
Or just ERB to work as in the https://github.com/tmuxinator/tmuxinator#erb .

**Environment**
 - tmuxinator Version: tmuxinator 0.6.11 # Hmm, Fedora has some archaic version?
- tmux Version: tmux 2.9a
 - Ruby Version: ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
 - OS: Fedora release 30 (Thirty)
