### ISSUE TITLE
main-horizontal causes tmux to crash

### ISSUE THREAD

**Issue by kleinjm** [tmuxinator/tmuxinator#732]
**Describe the bug**
Adding `layout: main-horizontal` causes tmux to crash after a few commands in a new session.

**To Reproduce**
- Have my versions of everything
- Create a config like this
```yml
name: whatever
root: ~/whatever
startup_pane: 1
windows:
  - editor:
      layout: main-horizontal
      panes:
        - vim .
        -
```

**Expected behavior**
The session begins and runs without crashing.

**Environment**
 - tmuxinator Version: 1.1.2
- tmux Version: 2.9a
 - Ruby Version: 2.6.3
 - OS: macOS Catalina 10.15.1

**Additional information**
This was not an issue until recently. The only change I can think of that would cause this is my upgrade to macOS Catalina as I've otherwise not touched my configurations at all recently. Here is [the commit to my dotfiles](https://github.com/kleinjm/dotfiles/commit/4cce3abd40ab7d41885d614d075c1752821ac879) that fixed this issue for me.
