### ISSUE TITLE
Resize pane height in first and third row to 4 lines in a 3x4 layout grid

### ISSUE THREAD

**Issue by Znote** [tmuxinator/tmuxinator#745]
Hahh.. I got tired of writing SSH all the time and was amazed to see that tmuxinator is my saving grace! 🎉  Now I can open up 18 SSH sessions in just one tmuxinator command! And **almost** get the tmux layout I want as well! I'm so close!

I got 6 TV dashboards in kiosk mode, using Raspberry Pi 4b machines. Its pretty awesome, but a bit bothersome to monitor. 👍 

I have a custom layout that currently generates a clean 3x4 layout grid. (3 columns, 4 rows). 
I want first and third row to only be 4 lines high, while the remaining rows takes the remaining available space. 

Is it possible to add the below commands to the `~/.tmuxinator/TVDashboards.yml` file so it resizes the appropriate rows to just be 4 lines high on the `startup_window`?
```yml
# First row
resize-pane -y 4 -t 0
resize-pane -y 4 -t 4
resize-pane -y 4 -t 8
# Third row
resize-pane -y 4 -t 2
resize-pane -y 4 -t 6
resize-pane -y 4 -t 10
```
(Right now I need to manually type them: CTRL + b : resize-pane -y 4 -t 0)
... and so on for every 4 height pane. 

Here is my tmuxinator file:
```yml
# ~/.tmuxinator/TVDashboards.yml

name: TVDashboards
root: ~/

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
startup_window: monitor

# Specitifes (by index) which pane of the specified window will be selected on project startup. If not set, the first pane is used.
startup_pane: 7

windows:
  - monitor:
      layout: 5c99,317x85,0,0{104x85,0,0[104x4,0,0,0,104x37,0,5,6,104x4,0,43,3,104x37,0,48,9],105x85,105,0[105x4,105,0,1,105x37,105,5,7,105x4,105,43,4,105x37,105,48,10],106x85,211,0[106x4,211,0,2,106x37,211,5,8,106x4,211,43,5,106x37,211,48,11]}
      # Synchronize all panes of this window, can be enabled before or after the pane commands run.
      # 'before' represents legacy functionality and will be deprecated in a future release, in favour of 'after'
      #synchronize: after
      panes:
        - ssh -t pi@rpifirstfloor 'sh measure_temp.sh; bash -l'
        - ssh -t pi@rpifirstfloor 'htop; bash -l'
        - ssh -t pi@rpifourthfloor 'sh measure_temp.sh; bash -l'
        - ssh -t pi@rpifourthfloor 'htop; bash -l'
        - ssh -t pi@rpisecondfloor 'sh measure_temp.sh; bash -l'
        - ssh -t pi@rpisecondfloor 'htop; bash -l'
        - ssh -t pi@brannfjellpi 'sh temps.sh; bash -l'
        - ssh -t pi@brannfjellpi 'htop; bash -l'
        - ssh -t pi@rpithirdfloor 'sh measure_temp.sh; bash -l'
        - ssh -t pi@rpithirdfloor 'htop; bash -l'
        - ssh -t pi@rpikantine 'sh measure_temp.sh; bash -l'
        - ssh -t pi@rpikantine 'htop; bash -l'
  - work:
      layout: c5bd,317x85,0,0{104x85,0,0[104x42,0,0,2,104x42,0,43,3],105x85,105,0[105x42,105,0,6,105x42,105,43,7],106x85,211,0[106x42,211,0,10,106x42,211,43,11]}
      panes:
        - ssh pi@rpifirstfloor
        - ssh pi@rpifourthfloor
        - ssh pi@rpisecondfloor
        - ssh pi@brannfjellpi
        - ssh pi@rpithirdfloor
        - ssh pi@rpikantine
```
Current results:
![image](https://user-images.githubusercontent.com/1552144/74448504-60c9c000-4e7b-11ea-817b-bb4994292364.png)

Desired results:
![image](https://user-images.githubusercontent.com/1552144/74448443-41cb2e00-4e7b-11ea-935a-3fb386cd4c43.png)

**Comment by Znote** [comment]
Solved!

I just added a new window called "setup" (found the trick by stalking closed issues). 
The tmux commands couldn't be directly used, somehow I needed to use "sleep && tmux..." to let the system breathe a bit before these adjustments. During trial and error I noticed it would sometimes work, which made me try this out. 

```yml
# ~/.tmuxinator/TVDashboards.yml

name: TVDashboards
root: ~/

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
startup_window: monitor

# Specitifes (by index) which pane of the specified window will be selected on project startup. If not set, the first pane is used.
startup_pane: 7

windows:
  - monitor:
      layout: 5c99,317x85,0,0{104x85,0,0[104x4,0,0,0,104x37,0,5,6,104x4,0,43,3,104x37,0,48,9],105x85,105,0[105x4,105,0,1,105x37,105,5,7,105x4,105,43,4,105x37,105,48,10],106x85,211,0[106x4,211,0,2,106x37,211,5,8,106x4,211,43,5,106x37,211,48,11]}
      panes:
        - ssh -t pi@rpifirstfloor 'sh measure_temp.sh; bash -l'
        - ssh -t pi@rpifirstfloor 'htop; bash -l'
        - ssh -t pi@rpifourthfloor 'sh measure_temp.sh; bash -l'
        - ssh -t pi@rpifourthfloor 'htop; bash -l'
        - ssh -t pi@rpisecondfloor 'sh measure_temp.sh; bash -l'
        - ssh -t pi@rpisecondfloor 'htop; bash -l'
        - ssh -t pi@brannfjellpi 'sh temps.sh; bash -l'
        - ssh -t pi@brannfjellpi 'htop; bash -l'
        - ssh -t pi@rpithirdfloor 'sh measure_temp.sh; bash -l'
        - ssh -t pi@rpithirdfloor 'htop; bash -l'
        - ssh -t pi@rpikantine 'sh measure_temp.sh; bash -l'
        - ssh -t pi@rpikantine 'htop; bash -l'
  - work:
      layout: c5bd,317x85,0,0{104x85,0,0[104x42,0,0,2,104x42,0,43,3],105x85,105,0[105x42,105,0,6,105x42,105,43,7],106x85,211,0[106x42,211,0,10,106x42,211,43,11]}
      panes:
        - ssh pi@rpifirstfloor
        - ssh pi@rpifourthfloor
        - ssh pi@rpisecondfloor
        - ssh pi@brannfjellpi
        - ssh pi@rpithirdfloor
        - ssh pi@rpikantine
  - setup:
      panes:
        - sleep 1 && tmux resize-pane -y 4 -t monitor.0
        - sleep 1 && tmux resize-pane -y 4 -t monitor.4
        - sleep 1 && tmux resize-pane -y 4 -t monitor.8
        - sleep 2 && tmux resize-pane -y 4 -t monitor.2
        - sleep 2 && tmux resize-pane -y 4 -t monitor.6
        - sleep 2 && tmux resize-pane -y 4 -t monitor.10
        - sleep 3 && tmux kill-window -t setup
```
