### ISSUE TITLE
Window numbers not set correctly

### ISSUE THREAD

**Issue by Santiniis** [tmuxinator/tmuxinator#747]
**Describe the bug**
Asking tmux to set the window number by tmuxinator will make tmux run the command while focusing only on the first window of the project, making it unavailable to set the window number on different windows other than the first window.

**To Reproduce**
- Create a project with three windows, a b and c;
- Set the number of window c to be something higher (example, 99);
- Run the project

**Expected behavior**
- Window c should be set as c: 99.

**Resulting behavior**
- Window c is created, and afterwards, window a is set as a:99.

**Environment**
 - tmuxinator Version: 1.1.4
 - tmux Version: 3.0a
 - Ruby Version:  2.3.7p456 
 - OS: macOs 10.14.5

**Comment by ethagnawl** [comment]
Hi,

I'll try to take a look at this when I can.

To glean some more information and try to weed out common issues:
- what values are you using for `base-index` and `pane-base-index`?
- could you share a sanitized version of the misbehaving project config file?

**Comment by Santiniis** [comment]
```yaml
name: foo
root: ~/
tmux_options: -f ~/.tmux.conf

windows:
  - infra:
      layout: tiled
      panes:
        - ruby_server:
          - cd ~/aquele_ruby_server_bem_basico
          - make some_server
        - redis-server
        - vtop
  - services:
      layout: even-horizontal
      panes:
        - some_service:
          - cd ~/SomeServices
          - make services
        - another_services:
          - cd ~/AnotherServices
          - make another_services
  - java_console_bugga:
      layout: tiled
      panes:
        - java_server:
          - cd ~/Documents/some_java_project
          - make
  - code:
      layout: tiled
      panes:
        - some_server_code:
          - cd ~/some_dir
          - nvim .
  - love: tiny-care-terminal
  - sim: tmux move-window -t 99; cd ~/sim/
```
