### ISSUE TITLE
Neovim not opening to full size of pane

### ISSUE THREAD

**Issue by sethen** [tmuxinator/tmuxinator#751]
**Describe the bug**
When using the command `nvim` in a pane task neovim sometimes will not open all the way to take up the entirety of the pane.

When you close neovim and reopen it, it will take up the space as you would expect it to.

Here's how it looks when you use `tmuxinator start <project>`:

![Screenshot from 2020-04-20 19-13-49](https://user-images.githubusercontent.com/1493530/79808283-5b856780-833b-11ea-926a-13be9966e8c9.png)

**To Reproduce**
Using the Neovim nightly build here:

```
windows:
  - dotfiles:
      layout: 7937,190x48,0,0[190x34,0,0,0,190x13,0,35{95x13,0,35,1,94x13,96,35,2}]
      panes:
        - ~/Developer/nvim.appimage
        -
        -
```
Then fire up `tmuxinator`.

**Expected behavior**
This is how it should look.  This does work when you close neovim that tmuxinator opened and then reopen neovim:

![Screenshot from 2020-04-20 19-17-23](https://user-images.githubusercontent.com/1493530/79808384-a901d480-833b-11ea-9a39-917a0bd8fd6c.png)

**Environment**
 - tmuxinator Version: tmuxinator 1.1.4
- tmux Version: tmux 2.6
 - Ruby Version: ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-linux]
 - OS: Ubuntu 18.04.04 LTS

**Additional information**
Add any other context or (potentially) useful information about the problem here. Feel free to include screenshots, videos, scripts, Dockerfiles, etc. which may help others diagnose/reproduce the issue.

**Comment by sethen** [comment]
I actually was able to fix this by upgrading to the newest version of tmux.  If anyone is having issues, that's where I would start.

**Comment by jesperp** [comment]
I am still getting this with

* Neovim v0.4.4
* tmuxinator 2.0.2
* tmux 3.1c
* macOS 10.14.6

Simply layout in yml:

```yml
windows:
  - editor:
      layout: main-horizontal
      panes:
        - nvim src/App.res
        - pnpm start

```

@sethen btw, what version of nvim were you using? Seeing that latest tmux didn't solve it for me
