### ISSUE TITLE
Best way to have a pane run the shell?

### ISSUE THREAD

**Issue by dakotahp** [tmuxinator/tmuxinator#775]
I have a setup where I have a window that has a pane with Ruby on Rails console and then have a pane that is just the shell (zsh in my case) and was wondering if there was a better way to handle it than what I'm doing.

I have it set to just run `zsh` and I'm afraid it's a Inception kind of scenario with a shell within a shell. It works perfectly fine but I'm curious if there's a better way. It seems that the gem loads up the shell and _then_ runs a command so conceivably it could _not_ run a command and just leave it at the shell prompt. 🤷🏼‍♂️ I suppose I can change it to something basic like an echo instead.

```
  42   │  windows:
  43   │   - servers:
  44   │       layout: even-vertical
  48   │       panes:
  49   │         - bundle exec rails s
  50   │         - ./bin/webpack-dev-server
  51   │   - workspace:
  52   │       layout: even-vertical
  53   │       panes:
  54   │         - bundle exec rails c
  55   │         - zsh
```

**Comment by ethagnawl** [comment]
Leaving an empty entry will result in a pane containing your default shell.

Using the config you've provided:

```
windows:
 - servers:
     layout: even-vertical
     panes:
       - bundle exec rails s
       - ./bin/webpack-dev-server
 - workspace:
     layout: even-vertical
     panes:
       - bundle exec rails c
       - # shell
```
