### ISSUE TITLE
GEM_HOME is set in my shell when tmuxinator runs

### ISSUE THREAD

**Issue by marcw** [tmuxinator/tmuxinator#776]
**Describe the bug**

warning: I'm a complete ruby noob, but I've got bitten multiple times by this.

The `GEM_HOME` environment variable is set in my shell when tmuxinator runs. This creates various undesirable side effects when running Ruby scripts. 

**To Reproduce**

- Create the `~/.config/tmuxinator/foobar.yml` configuration file (see below)
- Create a `tm` executable file with content somewhere in your PATH.
```
#!/bin/zsh
tmuxinator start foobar
```
- Run `tm` in your shell.

**Expected behavior**

I would like tmuxinator to not set the `GEM_HOME` environment variable, so that it doesn't mess with any `gem install`. Or, alternatively, I would like my `gem install` not messed up when running inside tmuxinator.

**Environment**
 - tmuxinator Version: 1.1.5 
- tmux Version: 3.1
 - Ruby Version: ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
 - OS: macOS Catalina

**Additional information**

Content of my tmuxinator configuration file:

```
# /Users/marc/.config/tmuxinator/foobar.yml

name: marc
root: ~/

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
startup_window: bf:root

windows:
  - dashboard:
      layout: main-vertical
      panes:
        - wtfutil

  - tools:
      layout: d4f0,178x45,0,0{89x45,0,0,9,88x45,90,0[88x22,90,0,14,88x22,90,23,15]}
      panes:
        - org ls 
        - 
        -

  - general:
      layout: even-horizontal
      panes:
        -
        -

  - bf:root:
      layout: even-horizontal
      root: "~/foo/bar"
      panes:
        -
        -
  - bf:private:
      layout: e703,178x48,0,0{89x48,0,0[89x24,0,0,16,89x23,0,25,18],88x48,90,0,17}
      root: ~/foo/bar
      panes:
        - 'cd baz'
        - 'cd baz'
        - 'cd baz'

  - bf:python:
      root: ~/foo/bar

  - bf:go:
      root: ~/foo/bar

  - bf:ruby:
      root: ~/foo/bar

```
