### ISSUE TITLE
Panes/windows crashing when starting a project

### ISSUE THREAD

**Issue by dspacejs** [tmuxinator/tmuxinator#777]
**Describe the bug**
When I start a project, some of my panes/windows are closing within a few seconds. If I manually run the same commands in these panes afterwards, it works, so I don't know why it's crashing on startup.

It's also worth noting only some of these panes/windows are crashing (I've noted them below in the config file). It happens every time I start the project.

I know you can run `tmux -v` to debug this, but I don't know how to configure tmuxinator to get tmux to do this. Therefore I'm not sure how to debug this.

**To Reproduce**
I'm unsure how to reproduce this.

**Expected behavior**
It shouldn't crash the pane/windows. If there's some sort of error, it should output that in the console.

**Environment**
 - tmuxinator Version: tmuxinator 1.1.4
- tmux Version: tmux 3.0a
 - Ruby Version: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
 - OS: Ubuntu 20.04 LTS

**Additional information**
This is the config file for my project:

```yml
name: vero
root: /home/daniel/Dev/freelance/vero
on_project_start: code .
startup_window: client
startup_pane: 3

windows:
  - client:
      root: /home/daniel/Dev/freelance/vero/front-end
      layout: even-horizontal
      panes:
        - npm run dev # This pane crashes
        - npm run storybook
        - npm run test:watch
        - 
  - server:
      root: /home/daniel/Dev/freelance/vero/api
      layout: even-horizontal
      panes:
        - make start && make logs
        - make start && make db_shell
        - make start && make exec
        - 
  - shell: # This entire window crashes
      root: /home/daniel/Dev/freelance/vero
      layout: even-horizontal
      panes:
        - cd front-end
        - cd front-end
        - cd api
        - cd api
```
