### ISSUE TITLE
`root` parameter not working in tmux 3.1b and tmuxinator 2.0.2

### ISSUE THREAD

**Issue by timvdalen** [tmuxinator/tmuxinator#798]
**Describe the bug**
The `root` parameter is not working in tmux 3.1b and tmuxinator 2.0.2.

I recently upgraded to tmux 3.1b and when tmuxinator gave me a not-supported message, I upgraded that to 2.0.2.

**To Reproduce**
* Have a config with a `root` key, for instance:

```
name: test-root
root: ~/projects/test

windows:
  - test-main:
      layout: main-vertical
      panes:
        -
        - command1
        - command2
  - logs: tail -f log.log
```

* Run `mux start testroot`

**Expected behavior**
* tmuxinator starts a tmux session with `~/projects/test` as the base folder

Instead, the working directory of the created session is `~`.

**Environment**
 - tmuxinator Version: "tmuxinator 2.0.2"
- tmux Version: "tmux 3.1b"
 - Ruby Version: "ruby 2.6.4p104 (2019-08-28 revision 67798) [x86_64-cygwin]"
 - OS: Windows 10/Cygwin
