### ISSUE TITLE
Pre_window doesnt works on new pane

### ISSUE THREAD

**Issue by rusikf** [tmuxinator/tmuxinator#803]
**Describe the bug**
Run ctr+b + C -> It opens new pane but comman in pre_window doesn't run

**To Reproduce**
Steps to reproduce the behavior. 

**Expected behavior**
Command in pre window will run

**Environment**
tmuxinator 2.0.2
tmux 3.0a
ruby 2.6.4p104
Ubuntu latest 20x

**Additional information**
pre_window command runs on start tmuxinator but not in the new pane
# /home/rusikf/.config/tmuxinator/plexa.yml

```
name: elker
pre_window: rvm use 2.7.2@elker
windows:
  - server:
      root: ~/Work/elker-front
      layout: even-vertical
      panes:
        - yarn: ./scripts/start_frontend.sh
        - rails:
          - cd ~/Work/elker
          - kill_3000
          - rails s
  - frontend:
      root: ~/Work/elker-front/app
      layout: even-vertical
      panes:
        - vim .
  - backend:
      root: ~/Work/elker
      layout: even-vertical
      panes:
        - vim .

```
