### ISSUE TITLE
Failed to execute child process "tmuxinator" (No such file or directory) [Error on startup]

### ISSUE THREAD

**Issue by afridi26** [tmuxinator/tmuxinator#805]
**Describe the bug**
Hey,

I am trying to run the tmuxinator session on ubuntu startup (i.e., on every reboot a terminal should open and show the tmuxinator session). Previously I had configured a start applications as per guide from [here](https://askubuntu.com/questions/48321/how-do-i-start-applications-automatically-on-login) to open gnome-terminal and it is working , for example:

```
# this is the command
gnome-terminal --geometry=100x25+100+200 --command "journalctl -u data_collection.service -n 40 -f"
```

However, above approach is not good because I need to open multiple terminals which is difficult to handle on different screens and I found about tmuxinator. So, I installed and configured the tmuxinator. Now, I want to start a session on every reboot. But I am getting the error when the terminal is shown on startup. Below is my configurations:

Tmuxinator script:

```
# /home/agx/.config/tmuxinator/monitor.yml
name: monitor
root: ~/

windows:
  - status_things:
      layout: main-horizontal
      panes:
        - journalctl -u roscoreLaunch.service -n 40 -f
        - systemctl status ptp4l.service
        - systemctl status phc2sys.service
        - journalctl -u data_collection.service -n 40 -f
```

I created an entry in the following folder:
```
/home/agx/.config/autostart
```
`tmuxintaor-log.desktop` contents

```
[Desktop Entry]
Type=Application
Exec=gnome-terminal  --command "tmuxinator monitor"
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name[en_US]=tmuxintaor-logs
Name=Tmux
Comment[en_US]=
Comment=

```

~/.bashrc contents
```
# some other,bla bla......

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
export RBENV_VERSION=2.6.6
export EDITOR="/usr/bin/vim"
export PATH="$PATH:/home/agx/.rbenv/shims/tmuxinator

```
 my environment and  configuration. It is all yes.
 ```
tmuxinator doctor
Checking if tmux is installed ==> Yes
Checking if $EDITOR is set ==> Yes
Checking if $SHELL is set ==> Yes
```

**To Reproduce**
1. Create a desktop entry in /home/\<username\>/.config/autostart. 
2. Enable the script on startup, like mentioned [here](https://askubuntu.com/questions/48321/how-do-i-start-applications-automatically-on-login). Create tmuxinator session named monitor with configurations which are mentioned in the beginning and add the command to start application as:
```
gnome-terminal  --command "tmuxinator monitor"

```
3. reboot the system.

Error:

![tmux_error](https://user-images.githubusercontent.com/5488091/105691694-de0c0a80-5efd-11eb-8061-7a38fd7101a9.png)

**Expected behavior**

I should able to see the tmuxinator session on reboot.

**Environment**
 - tmuxinator Version: 2.0.2
- tmux Version: 2.6
 - Ruby Version: 2.6.6p146 (2020-03-31 revision 67876) [aarch64-linux]
 - OS: Ubuntu 18.04.5 LTS [Nvidia Agx]
