### ISSUE TITLE
Crashes with a couple windows and layout: main-vertical

### ISSUE THREAD

**Issue by coaxial** [tmuxinator/tmuxinator#810]
**Describe the bug**
Having more than a couple windows with `layout: main-vertical` often crashes tmuxinator.

**To Reproduce**
Given this config file:

```yaml
name: layout-repro
root: ~/
windows:
  - editor:
      layout: main-vertical
      panes:
        - nvim
        - nvim
  - server: nvim
  - logs: nvim
  - other:
      layout: main-vertical
      panes:
        - nvim
        - nvim
  - another:
      layout: main-vertical
      panes:
        - nvim
        - nvim
``` 
Run `mux start layout-repro`

Observe `tmuxinator` start and then crash half-way through after a few seconds with `[server exited unexpectedly]`.

The terminal must be reset with `reset` before it operates again normally.

It doesn't crash every time, about once every five times or so on my machine.

**Expected behavior**
`tmuxinator` to start properly without errors or crashes.

**Environment**
```
$ tmuxinator -v
tmuxinator 2.0.2

 $ tmux -V
tmux 3.0a

$ ruby -v
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

**Additional information**
See https://asciinema.org/a/vLXSTDZEb08o4iHwjz7rx7oTT
