### ISSUE TITLE
tmux cannot parse config file. (not even its own generated one)

### ISSUE THREAD

**Issue by jschank** [tmuxinator/tmuxinator#819]
**Describe the bug**
The only output I *ever* see from mux is:
`Failed to parse config file: wrong number of arguments (given 4, expected 1)`

**To Reproduce**
1. Create new project with `$ mux new foo`
2. Save file that appears in editor
3. run `$ mux foo`
4. Receive: `Failed to parse config file: wrong number of arguments (given 4, expected 1)`

**Expected behavior**
I expect my config - which was working, and is unchanged, to load.

**Environment**
 - tmuxinator Version: tmuxinator 2.0.3
 - tmux Version: tmux 3.2
 - Ruby Version: ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]
 - OS: macOS Bug Sur, Version 11.3.1

**Additional information**
- Using rbenv
-

**Comment by pbek** [comment]
I'm getting exactly the same after an update (don't know if of tmux or tmuxinator) on KDE Neon (based on Ubuntu 20.04). It worked last time on Monday.

tmux: 3.0a-2ubuntu0.3
tmuxinator 1.1.4


```yaml
name: deploy-qownnotes
windows:
  - deploy:
      layout: tiled
      panes:
        - launchpad:
            - ../ubuntu-launchpad/build-for-launchpad.sh
        - obs:
            - ../obs/build-for-obs.sh
        - aur:
            - aur/build-for-aur.sh
        - gentoo:
            - gentoo/build-for-gentoo.sh
        - slackware:
            - slackware/build-for-slackware.sh
        - snap:
            - snap/build-for-launchpad-snap.sh
```
