### ISSUE TITLE
Sed error when starting a session via tmuxinator

### ISSUE THREAD

**Issue by chreniuc** [tmuxinator/tmuxinator#831]
**Describe the bug**

When I try to start a session via tmuxinator, the session starts, the layout is created but the commands for panels are not ran. I've noticed that on every pane this error is printed: `sed: -e expression #1, char 231: unterminated address regex`

![error](https://user-images.githubusercontent.com/20834214/123955079-e0ddc080-d9b1-11eb-8788-007656fcd7e5.png)

**To Reproduce**

This is the config flie. But this happens to any config file I provide. Even the example from the main readme from tmuxinator.

```yaml
name: test

windows:
  - clients:
      layout: tiled
      panes:
        - ls
```
Command ran:

```
tmuxinator start test
```

**Expected behavior**

The ls command should be ran after the pane is created and the sed error shouldn't be present.

**Environment**
 - tmuxinator Version: `tmuxinator 1.1.4`
- tmux Version: `tmux 3.0a`
 - Ruby Version: `ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]`
 - OS: `Ubuntu 20.04.2 LTS`
 - sed: `sed (GNU sed) 4.7`
 
 Tmuxinator was installed from the Ubuntu repository:
 
 ```
 sudo apt-get install tmuxinator
 ```

**Additional information**

Did anyone encountered the same issue?

**Comment by chreniuc** [comment]
If I provide this config file:

```yaml
name: test

windows:
  - clients:
      layout: tiled
```

The error doesn't show anymore.
