### ISSUE TITLE
Window specific root not work

### ISSUE THREAD

**Issue by changyiyao** [tmuxinator/tmuxinator#835]
**Describe the bug**
My project yaml js as the following:
```
name: example
root: ~/Projects/example/modules

windows:
  - example1:
    root: ~/Projects/example/modules/example1
    panels:
      - nvim

```
Because of the root specified in windows.exmples1, the whole example1 execute nothing at all. (Commands in `panels` didn't work, which just cd to the root of project `~/Projects/example/modules`.

When I remove the windows.example1.root, commands in example1.panels works well(`nvim` is executed).

**To Reproduce**
Just start the project
```
tuxminator start example
```

**Expected behavior**
1. Window 'example1' should `cd` to `~/Projects/example/modules/example1`.
2. Window 'example1' should execute `nvim`

**Environment**
 - tmuxinator Version: 3.0.1
- tmux Version: tmux 3.2a
 - Ruby Version: ruby 2.6.8p205 (2021-07-07 revision 67951) [x86_64-darwin20]
 - OS: macOS 11.5.1 20G80 x86_64

**Additional information**

**Comment by j-a-m-l** [comment]
@changyiyao the problem is probably the indentation. Try
```yaml
name: example
root: ~/Projects/example/modules

windows:
  - example1:
      root: ~/Projects/example/modules/example1
      panels:
        - nvim
```

Using `tmuxinator debug example` can be used to see which commands are run by Tmuxinator.
