### ISSUE TITLE
best way to avoid code duplicate between project

### ISSUE THREAD

**Issue by StoryDevOffical** [tmuxinator/tmuxinator#840]
Hi, 

First, thanks for this awesome tool.
Now, I am asking what is the best way to include a project in another without to duplicate code.
I found some manners like use python, but there ... maybe there are good practices about.

best regards, 
story

**Comment by ethagnawl** [comment]
Hi, @StoryDevOffical.

This functionality isn't currently supported by tmuxinator or Yaml. However, if/when PR #652 lands, that should solve the same problem from a different angle.

Otherwise, I haven't every seriously tried to do this, but you _may_ be able to use ERB in your project's config file to inject Yaml snippets. YMMV, but something like:

```
# /home/user/.config/tmuxinator/two.yml

name: two
windows:
  - other_editor:
      layout: main-vertical
      panes:
        - echo "hi from two!"
```

```
# /home/user/.config/tmuxinator/one.yml

name: one
windows:
  <%= IO.read("./two.yml") %>
  - editor:
      layout: main-vertical
      panes:
        - echo "hi from one!"
```
