### ISSUE TITLE
Get session's name in erb?

### ISSUE THREAD

**Issue by Realetive** [tmuxinator/tmuxinator#845]
Hello! 👋  Is it possible to get custom sessions's name in config file?

```bash
$ tmuxinator start project -n tmuxinator
```

```yaml
# ~/.tmuxinator/project.yml

name: project
root: ~/projects/<%= @config["name"] %>

...
```

**Comment by ethagnawl** [comment]
Hi, @Realetive. 

I believe you're limited to using [the machinations outlined in the README](https://github.com/tmuxinator/tmuxinator#erb):

```
# /home/peter/.config/tmuxinator/config_name.yml

name: pre_window_hook
root: ~/<%= ENV["name"] %>
# root: ~/<%= @settings["name"] %>
# root: ~/<%= @args[0] %>
windows:
  - editor:
      panes:
        - echo hi
```
