### ISSUE TITLE
Don't run the commands appropriately

### ISSUE THREAD

**Issue by devrrior** [tmuxinator/tmuxinator#856]
**Describe the bug**
When I start one of my projects, the commands which I set to run in the panes don't run correctly.

**To Reproduce**
Just run `tmuxinator start project `

**Expected behavior**
I expected my windows to execute the commands correctly.

**Environment**
 - tmuxinator Version: 3.0.2
- tmux Version: 3.2a
 - Ruby Version:  3.1.1p18 
 - OS: macOS Monterrey version 12.3

**Additional information**
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/69869135/160057823-b706f0e9-e183-4fc9-b41a-42722b6a7df4.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/69869135/160057851-3989b9f0-4bfb-45cc-9ca4-d92a8680e908.png">
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/69869135/160057908-ed686944-8ba3-4cc4-922d-10651080a997.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/69869135/160057887-7a4741ae-14f3-4e80-b970-2c29694cf324.png">

**My config**
``` yaml
name: chat-message
root: ~/repos/chat-messages
on_project_start: docker-compose up -d
# on_project_exit: docker-compose down

windows:
  - frontend:
      root: ~/repos/chat-messages/frontend
      panes:
        - editor:
            - vim +'Telescope find_files'

  - backend:
      root: ~/repos/chat-messages/backend
      panes:
        - editor:
            - vim +'Telescope find_files'

  - server:
      layout: main-vertical
      panes:
        - react-server:
            - cd frontend/
            - clear
            - docker-compose logs --follow frontend

        - backend-server:
            - cd backend/
            - clear
            - docker-compose logs --follow backend
```

**Comment by devdrops** [comment]
Same issue here. I'm suspicious that this issue may happens on MacOS only, because this issue does not happen on my Linux environment.

- tmuxinator version: `tmuxinator 3.0.2`
- tmux version: `tmux 3.2a`
- ruby version: `ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]`
- From `echo $OSTYPE`: `darwin20.0`

Config file:

```yaml
# /Users/davimarcondesmoreira/.config/tmuxinator/my-dotfiles.yml

name: my-dotfiles
root: /Users/davimarcondesmoreira/Projects/Devdrops/etc/my-dotfiles

on_project_start: git fetch --all
startup_window: VIM
windows:
  - VIM: vim .
  - ENV:
    layout: even-horizontal
    panes:
      - git status
      - git status
  - GIT:
    layout: main-horizontal
    panes:
      - CURRENT_STATUS:
        - git status -u
      - FILES_AND_TIME:
        - tmux split-window -t 2.1 -h
        - tmux resize-pane -t 2.1 -R 40
        - tmux clock-mode -t 2.2
        - tmux send-keys -t 2.1 "git diff origin/main...`git rev-parse --abbrev-ref HEAD` --name-only --diff-filter=AM" Enter
```

Output from `show-messages`:

```
11:13: /dev/ttys000 command: show-messages
11:13: /dev/ttys000 key :: command-prompt
11:13: /dev/ttys000 command: attach-session -t my-dotfiles
11:13: /dev/ttys000 command: select-pane -t my-dotfiles:VIM.0
11:13: /dev/ttys000 command: select-window -t my-dotfiles:VIM
11:13: /dev/ttys000 command: send-keys -t my-dotfiles:0 "vim ." C-m
11:13: /dev/ttys000 command: new-window -c /Users/davimarcondesmoreira/Projects/Devdrops/etc/my-dotfiles -n GIT -t my-dotfiles:2
11:13: /dev/ttys000 command: new-window -c /Users/davimarcondesmoreira/Projects/Devdrops/etc/my-dotfiles -n ENV -t my-dotfiles:1
11:13: /dev/ttys000 command: send-keys -t my-dotfiles:0 "cd /Users/davimarcondesmoreira/Projects/Devdrops/etc/my-dotfiles" C-m
11:13: /dev/ttys000 command: new-session -d -n VIM -s my-dotfiles
```

**Comment by PrimaMateria** [comment]
Same issue also reproducible on Linux running in WSL2. I am installing from `apt` so in my case I have:

- tmux 3.2a
- tmuxinator 3.0.1
- ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-gnu]
- linux-gnu

**Comment by ignu** [comment]
Same here. I was setting up a new machine and absolutely losing it because I couldn't figure out what was wrong with my yml.

**Comment by caliguIa** [comment]
same here

**Comment by DefinitelyNotSimon13** [comment]
did anyone manage to fix this? same for me

**Comment by akofink** [comment]
If someone could give me the output of `tmuxinator debug <project>`, it might help debugging this issue. 🙇 

I am not able to reproduce it locally yet, but it seems similar to https://github.com/tmuxinator/tmuxinator/issues/909

**Comment by DefinitelyNotSimon13** [comment]
@akofink 

so for me the problem actually seems to be, that the keys are send before oh-my-posh is fully loaded. As such I assume the issue is not because of tmuxinator.

For good measure heres the output anyway:
```sh
#!/bin/zsh

# Clear rbenv variables before starting tmux
unset RBENV_VERSION
unset RBENV_DIR

tmux start-server;

cd /home/simon/1_Coding/todo-list

# Run on_project_start command.



  # Run pre command.


  # Run on_project_first_start command.


  # Create the session and the first window. Manually switch to root
  # directory if required to support tmux < 1.9
  TMUX= tmux new-session -d -s todo-list -n editor -c /home/simon/1_Coding/todo-list



  # Create other windows.
  tmux new-window -c /home/simon/1_Coding/todo-list -t todo-list:2 -n bacon


  # Window "editor"

  tmux set-window-option -t todo-list:1 pane-border-status top
  tmux set-window-option -t todo-list:1 pane-border-format "#{pane_index}: #{pane_title}"


  tmux send-keys -t todo-list:1.1 nvim C-m

  tmux splitw -c /home/simon/1_Coding/todo-list -t todo-list:1
  tmux select-layout -t todo-list:1 tiled

  tmux send-keys -t todo-list:1.2 cargo\ check C-m

  tmux select-layout -t todo-list:1 tiled

  tmux select-layout -t todo-list:1 main-vertical
  tmux select-pane -t todo-list:1.1


  # Window "bacon"

  tmux set-window-option -t todo-list:2 pane-border-status top
  tmux set-window-option -t todo-list:2 pane-border-format "#{pane_index}: #{pane_title}"

  tmux send-keys -t todo-list:2 bacon\ clippy C-m


  tmux select-window -t todo-list:1
  tmux select-pane -t todo-list:1.1

  if [ -z "$TMUX" ]; then
    tmux -u attach-session -t todo-list
  else
    tmux -u switch-client -t todo-list
  fi



# Run on_project_exit command.
```

**Comment by akofink** [comment]
That makes sense! Thank you for this insight, it is really useful. 💯

**Comment by DefinitelyNotSimon13** [comment]
ofc!

For anyone who might come across this later on, a workaround that worked for me:
I use [zsh-defer](https://github.com/romkatv/zsh-defer) on the `eval "$(oh-my-posh init zsh ...)"` command.
To avoid showing the default for a split second, I also set `PS1=""` at the beginning of my .zshrc file.

```sh
# .zshrc
PS1=""
# [...]

zsh-defer eval "($oh-my-posh) init zsh --config [...]
```

**Comment by jasper-at-windswept** [comment]
@DefinitelyNotSimon13 
I'm having this same issue on NixOS, neovim just doesn't open but it shows the command above oh-my-posh.
I applied the above mentioned fix but it did not work.

Here is my project:
```yml
name: nodenvim
root: /run/media/allusive/SSD/Projects/NodeProjects/

windows:
  - editor:
      layout: cf13,204x46,0,0{147x46,0,0[147x34,0,0,0,147x11,0,35,2],56x46,148,0,1}
      # synchronize: after
      panes:
      - neovim:
        - nvim
      - #empty
      - #empty
```
