### ISSUE TITLE
Need help!!!

### ISSUE THREAD

**Issue by 0xhunster** [tmuxinator/tmuxinator#869]
Tmuxinator is great. Sir, I saw your this code. But I want to run 4 VPS and multiple commands with a single tmux screen. like this image. So, what will my config file look like? Give me a demo. please, please, please

![image](https://user-images.githubusercontent.com/46501627/192369771-e02cabc1-eec9-4d6f-8715-04fc5ded65de.png)

```
name: sample
root: ~/

windows:
  - stats:
    - ssh stats@example.com
    - tail -f /var/log/stats.log
  - logs:
      layout: main-vertical
      panes:
        - logs:
          - ssh logs@example.com
          - cd /var/logs
          - tail -f development.log
```

**Comment by ethagnawl** [comment]
This should be enough to go on:

```
name: 869
windows:
    - editor:
        layout: tiled
        panes:
          - one:
            - echo one
          - two:
            - echo two
          - three:
            - echo three
          - four:
            - echo four
```
