### ISSUE TITLE
Can make tmuxinator to open a terminal for each declared window?

### ISSUE THREAD

**Issue by schoettl** [tmuxinator/tmuxinator#877]
Sorry, this is rather a question than a feature request.

Can tmuxinator automatically start new terminal windows, each hosting a single tmux window?

I use a tiling window manager and also tmux. And with tmuxinator it seems so easy to re-open the dev env which is about this:

```yaml
windows:
  - elm-watch: cd elm/ && npx elm-watch hot
  - servers-and-stuff:
      layout: vertical
      panes:
        - cd elm/ && python3 -m http.server --bind localhost
        - nix-shell --run './webaccess/manage.py runserver 8001'
        - cd elm/ && watchexec -e hs,ftl make
  - translations: cd elm/ && vim -nd lang/*.ftl
```

But I would prefer to have each tmux window in a separate terminal window.
