### ISSUE TITLE
Select focused pane for each window

### ISSUE THREAD

**Issue by mpeter50** [tmuxinator/tmuxinator#878]
**Is your feature request related to a problem? Please describe.**

For windows that have multiple panes, I often have to navigate to the primary pane (which is not necessarily the largest in the layout) manually.

**Describe the solution you'd like**

There could be a window level option where the number or the name of the pane could be given, like `focused_pane` in the example below:

```
name: sample
root: ~/

windows:
  - stats:
    - tail -f /var/log/stats.log
  - logs:
      layout: main-vertical
      focused_pane: example
      panes:
        - logs:
          - tail -f development.log
        - example:
          - echo 'example 2nd pane'
```

(the `focused_pane` setting may also accept the pane number for the same effect)

**Describe alternatives you've considered**

An other solution could be having a pane level boolean option for designating the pane to be focused, however considering that panes are always lists of commands to be executed, this would probably also involve a larger change, like moving commands to be under a `commands` list inside the pane.

**Additional context**
There were already attempts of similar feature requests, but they were closed with a change that did not solve the request.
- #455 was closed saying that it is already possible to designate a focused pane, but that only applies for the starting window, even though the issue requested the ability for each window separately too
- #52 was closed with a merge request that changed how the default active pane selection works for each window, without making it configurable, so that it works for that specific situation that was brought up as an example by the issue author, but also does not fulfill the actual feature request
