### ISSUE TITLE
ERB Incorrectly Parses Character

### ISSUE THREAD

**Issue by JaredStemper** [tmuxinator/tmuxinator#879]
**ERB Incorrectly Parses the '=' character**
Passing a parameter into a tmuxinator script with a '=' strips the rest of the string in that parameter away.

For an example, if using the command `mux start -p ./template.yml value='set value = this`, accessing the `value` variable later will only result in `set value` instead of `set value = this`.

**To Reproduce**
To pass in a variable into a tmuxinator script using ERB, the README guidance is as follows:
`mux start -p ./template.yml value='set value = this'`

To set variable in the template YAML file itself:
`@settings["value"] ||= "testing=set value = this"`

To read a variable in the YAML file:
`<%= @settings["value"] %>`

Using a skeleton project as an example, with a `value` variable set to `set value = this`:
```YAML
name: testing
root: ~

<%
  @settings["value"] ||= "set value = this"
%>

# create and cd into client/testing folder before running
windows:
  - testing: echo '"<%= @settings["value"] %>"'
```

When the variable is set with @settings["user"] it works as expected:
![image](https://github.com/tmuxinator/tmuxinator/assets/31346981/622da89b-2e7e-4cc5-85ce-45c06980e5d6)

When the variable is passed through the command line as ``, the result is stripped:
![image](https://github.com/tmuxinator/tmuxinator/assets/31346981/6b6e5529-24e8-4d71-894a-f3b160a88b28)

**Environment**
 - tmuxinator Version: tmuxinator 3.0.5
- tmux Version: tmux 3.3a
 - Ruby Version: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux-gnu]
 - OS: Kali GNU/Linux Rolling; Version_ID=2023.3 (inside VMWare)
