### ISSUE TITLE
Complex layouts don't seem to work

### ISSUE THREAD

**Issue by aberios** [tmuxinator/tmuxinator#89]
e.g. 

```
tabs:
  - shell:
      layout: a506,379x84,0,0{125x84,0,0[125x26,0,0,4,125x31,0,27,83,125x25,0,59,82],125x84,126,0[125x42,126,0,79,125x41,126,43,86],127x84,252,0[127x27,252,0,80,127x30,252,28,84,127x25,252,59,85]}
      panes:
        - echo 1
        - echo 2
        - echo 3
        - echo 4
        - echo 5
        - echo 6
        - echo 7
        - echo 8
```

Only creates 5 panes
