### ISSUE TITLE
Unable to get layout to appear on both MacOS & Ubuntu

### ISSUE THREAD

**Issue by jaoxford** [tmuxinator/tmuxinator#912]
**Describe the bug**
I'm having an issue with my config file. Previously my layouts were working until I decided to delete my tmuxinator project & reinitialise it. Now I'm not seeing my window split into panes.

**To Reproduce**
Here's my file which is called `fullpush.yml`, it's located in `~/config/tmuxinator/fullpush.yml`

```yaml
name: fullpush
enable_pane_titles: true
windows:
  - main: null
    layout: tiled
    panes:
      - service:
          - ' cd ~/Projects/scorecard-service && clear'
      - library:
          - ' cd ~/Projects/scorecard-library && clear'
      - simulator:
          - ' cd ~/Projects/scorecard-simulator && clear'
      - webapp:
          - ' cd ~/Projects/scorecard-webapp && clear'
  - helm:
      - ' cd ~/Projects/scorecard-helm && clear'
```

Nothing too crazy here, I'm opening two windows, one window has 4 panes, and the other has a single pane. 
And I then cd into the appropriate repository for each window / pane, and then clear the screen.

Steps to reproduce the behavior.

I went to a new machine, copied my file above into `~/config/tmuxinator/fullpush.yml`, then ran `tmuxinator start -p ~/.config/tmuxinator/fullpush.yml` for the initial loading. And instead of seeing 4 panes, I only see one.

**Expected behavior**

I would expect my first window to be split into 4 separate panes.

**Environment**
 - tmuxinator Version: tmuxinator 3.1.2
- tmux Version: tmux 3.4
 - Ruby Version: ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin23]
 - OS: macOS Sonoma 14.3

**Comment by akofink** [comment]
Hey there - thanks for reporting this!

It looks like the project config isn't quite right, missing a level of indentation under the `main` window, and there's an added `null` after `main`. Please try the following project config, and notice the difference when parsed to ruby:

```
name: fullpush
windows:
  - main:
      layout: tiled
      panes:
        - service:
            - ' cd ~/Projects/scorecard-service && clear'
        - library:
            - ' cd ~/Projects/scorecard-library && clear'
        - simulator:
            - ' cd ~/Projects/scorecard-simulator && clear'
        - webapp:
            - ' cd ~/Projects/scorecard-webapp && clear'
  - helm:
      - ' cd ~/tmp && clear'
```

```rb
[3] pry(main)> YAML.load_file('fullpush_good.yml')
=> {"name"=>"fullpush",
 "windows"=>
  [{"main"=>
     {"layout"=>"tiled",
      "panes"=>
       [{"service"=>[" cd ~/tmp && clear"]},
        {"library"=>[" cd ~/tmp && clear"]},
        {"simulator"=>[" cd ~/tmpor && clear"]},
        {"webapp"=>[" cd ~/tmp && clear"]}]}},
   {"helm"=>[" cd ~/tmp && clear"]}]}

[4] pry(main)> YAML.load_file('fullpush_bad.yml')
=> {"name"=>"fullpush",
 "windows"=>
  [{"main"=>nil,
    "layout"=>"tiled",
    "panes"=>
     [{"service"=>[" cd ~/tmp && clear"]},
      {"library"=>[" cd ~/tmp && clear"]},
      {"simulator"=>[" cd ~/tmpor && clear"]},
      {"webapp"=>[" cd ~/tmp && clear"]}]},
   {"helm"=>[" cd ~/tmp && clear"]}]}
```

Please let me know if this doesn't fix the issue you're seeing.
